// 客户端 JavaScript 模板
// 使用数组 join 方式返回 script 标签，避免模板字符串嵌套问题
export function getClientScript() {
  const lines = [
    '<script>',
    '    const {host,protocol}=window.location;',
    "    let baseUrl='https://brew-cn.mintimate.cn';",
    "    if(host&&!/localhost|127\\.0\\.0\\.1/.test(host)&&protocol!=='file:') baseUrl=protocol+'//'+host;",
    '    document.getElementById(\'install-command\').textContent=\'/bin/zsh -c \"$\'+\'(curl -fsSL \'+baseUrl+\'/install)\"\';',
    '    document.getElementById(\'uninstall-command\').textContent=\'/bin/zsh -c \"$\'+\'(curl -fsSL \'+baseUrl+\'/install)\" -- --uninstall\';',
    '',
    '    function copyCommand(id,btn){',
    '        const text=document.getElementById(id).textContent,orig=btn.textContent;',
    "        const done=()=>{btn.textContent='已复制!';btn.classList.add('copied');setTimeout(()=>{btn.textContent=orig;btn.classList.remove('copied')},2000)};",
    "        navigator.clipboard.writeText(text).then(done).catch(()=>{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');document.body.removeChild(t);done()});",
    '    }',
    '',
    '    function renderRecentInstalls(installs){',
    "        const container=document.getElementById('recent-installs');",
    '        if(!installs||installs.length===0){',
    '            container.innerHTML=\'<div class="recent-placeholder" style="text-align:center;color:var(--text-muted);font-size:.9rem;padding:16px 0">暂无安装记录</div>\';',
    '            return;',
    '        }',
    '        container.innerHTML=installs.map(item=>{',
    "            const filterUnknown = (val) => val && !val.toLowerCase().includes('unknown') ? val : '';",
    "            const loc=[filterUnknown(item.city),filterUnknown(item.region),filterUnknown(item.country)].filter(Boolean).join(', ')||'未知地区';",
    '            const dt=new Date(item.time);',
    '            const ms=Date.now()-dt,m=ms/6e4|0,h=ms/36e5|0,dy=ms/864e5|0;',
    "            const ago=m<1?'刚刚':m<60?m+'分钟前':h<24?h+'小时前':dy<30?dy+'天前':dt.toLocaleDateString('zh-CN');",
    '            return \'<div class="recent-item"><span class="ri-icon">📍</span><span class="ri-location" title="\'+loc+\'">\'+loc+\'</span><span class="ri-ip">\'+(item.ip||\'\')+\'</span><span class="ri-time">\'+ago+\'</span></div>\';',
    "        }).join('');",
    '    }',
    '',
    '    async function fetchStats(){',
    '        try{',
    "            const r=await(await fetch('/api/stats')).json();",
    '            if(r.code!==0)return;',
    "            document.getElementById('total-calls').textContent=r.data.totalCalls.toLocaleString();",
    '            const t=r.data.lastCallTime;',
    "            if(!t){document.getElementById('last-call').textContent='暂无记录';return}",
    '            const d=new Date(t),ms=Date.now()-d,m=ms/6e4|0,h=ms/36e5|0,dy=ms/864e5|0;',
    "            const ago=m<1?'刚刚':m<60?m+' 分钟前':h<24?h+' 小时前':dy<30?dy+' 天前':d.toLocaleDateString('zh-CN');",
    "            const el=document.getElementById('last-call');el.textContent=ago;el.title=d.toLocaleString('zh-CN');",
    '            renderRecentInstalls(r.data.recentInstalls||[]);',
    "        }catch(e){console.error('获取统计数据失败:',e)}",
    '    }',
    '',
    "    document.addEventListener('DOMContentLoaded',()=>{",
    '        fetchStats();setInterval(fetchStats,3e4);',
    "        const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('active');ob.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -50px 0px'});",
    "        document.querySelectorAll('.reveal').forEach(el=>ob.observe(el));",
    '    });',
    '</script>',
  ];
  return '\n    ' + lines.join('\n');
}
