// 客户端 JavaScript 模板
// 使用数组 join 方式返回 script 标签，避免模板字符串嵌套问题
export function getClientScript() {
  const lines = [
    '<script>',
    '    const {host,protocol}=window.location;',
    "    let baseUrl='https://brew-cn.mintimate.cn';",
    "    if(host&&!/localhost|127\\.0\\.0\\.1/.test(host)&&protocol!=='file:') baseUrl=protocol+'//'+host;",
    '',
    '    // Update macOS commands',
    '    const macInstall=document.getElementById(\'install-command-macos\');',
    '    const macUninstall=document.getElementById(\'uninstall-command-macos\');',
    '    if(macInstall) macInstall.textContent=\'/bin/zsh -c "$\'+\'(curl -fsSL \'+baseUrl+\'/install)"\';',
    '    if(macUninstall) macUninstall.textContent=\'/bin/zsh -c "$\'+\'(curl -fsSL \'+baseUrl+\'/install)" -- --uninstall\';',    '',
    '    // Update Linux commands',
    '    const linInstall=document.getElementById(\'install-command-linux\');',
    '    const linUninstall=document.getElementById(\'uninstall-command-linux\');',
    '    if(linInstall) linInstall.textContent=\'/bin/bash -c \"$\'+\'(curl -fsSL \'+baseUrl+\'/install)\"\';',
    '    if(linUninstall) linUninstall.textContent=\'/bin/bash -c \"$\'+\'(curl -fsSL \'+baseUrl+\'/install)\" -- --uninstall\';',
    '',
    '    // OS tab switching',
    '    window.switchOS=function(os){',
    '        document.querySelectorAll(\'.os-tab\').forEach(t=>{t.classList.toggle(\'active\',t.dataset.os===os)});',
    '        document.querySelectorAll(\'.os-panel\').forEach(p=>{p.style.display=\'none\'});',
    '        const panel=document.getElementById(\'os-\'+os);',
    '        if(panel) panel.style.display=\'block\';',
    '    };',
    '',
    '    // Auto-detect OS from User-Agent',
    '    (function(){',
    '        const ua=navigator.userAgent||navigator.platform||\'\';',
    '        if(/Linux/i.test(ua)&&!/Android/i.test(ua)) switchOS(\'linux\');',
    '    })();',
    '',
    '    function copyCommand(id,btn){',
    '        const text=document.getElementById(id).textContent,orig=btn.textContent;',
    "        const done=()=>{btn.textContent='已复制!';btn.classList.add('copied');setTimeout(()=>{btn.textContent=orig;btn.classList.remove('copied')},2000)};",
    "        if(navigator.clipboard){navigator.clipboard.writeText(text).then(done).catch(done)}else{const t=document.createElement('textarea');t.value=text;t.style.cssText='position:fixed;opacity:0';document.body.appendChild(t);t.select();document.execCommand('copy');document.body.removeChild(t);done()}",
    '    }',
    '',
    '    const THEME_KEY=\'brew-cn-theme\';',
    '    const mediaDark=window.matchMedia(\'(prefers-color-scheme: dark)\');',
    '    const THEME_MODES=[\'light\',\'system\',\'dark\'];',
    '    function getSavedThemeMode(){',
    '        const saved=localStorage.getItem(THEME_KEY);',
    '        return THEME_MODES.includes(saved)?saved:\'system\';',
    '    }',
    '    function resolveTheme(mode){',
    '        return mode===\'system\'?(mediaDark.matches?\'dark\':\'light\'):mode;',
    '    }',
    '    function getModeLabel(mode){',
    '        return mode===\'light\'?\'亮色\':mode===\'dark\'?\'暗色\':\'跟随系统\';',
    '    }',
    '    function applyThemeMode(mode,{persist=false}={}){',
    '        const resolved=resolveTheme(mode);',
    '        document.documentElement.setAttribute(\'data-theme\',resolved);',
    '        const toggle=document.getElementById(\'theme-toggle\');',
    '        if(toggle){',
    '            toggle.dataset.theme=mode;',
    '            toggle.setAttribute(\'aria-label\',\'切换主题（当前\'+getModeLabel(mode)+\'）\');',
    '            toggle.setAttribute(\'title\',\'当前：\'+getModeLabel(mode)+\'（点击切换）\');',
    '        }',
    '        if(persist) localStorage.setItem(THEME_KEY,mode);',
    '    }',
    '    function nextThemeMode(current){',
    '        const idx=THEME_MODES.indexOf(current);',
    '        return THEME_MODES[(idx+1)%THEME_MODES.length];',
    '    }',
    '    function setupThemeToggle(){',
    '        applyThemeMode(getSavedThemeMode());',
    '        const toggle=document.getElementById(\'theme-toggle\');',
    '        if(toggle){',
    '            toggle.addEventListener(\'click\',()=>{',
    '                const current=toggle.dataset.theme||getSavedThemeMode();',
    '                applyThemeMode(nextThemeMode(current),{persist:true});',
    '            });',
    '        }',
    '        const handleChange=()=>{',
    '            if(getSavedThemeMode()===\'system\') applyThemeMode(\'system\');',
    '        };',
    '        if(mediaDark.addEventListener) mediaDark.addEventListener(\'change\',handleChange);',
    '        else if(mediaDark.addListener) mediaDark.addListener(handleChange);',
    '    }',
    '',
    '    const fu=v=>v&&!/unknown/i.test(v)?v:\'\';',
    '    function timeAgo(t){const d=new Date(t),ms=Date.now()-d,m=ms/6e4|0,h=ms/36e5|0,dy=ms/864e5|0;return m<1?\'刚刚\':m<60?m+\'分钟前\':h<24?h+\'小时前\':dy<30?dy+\'天前\':d.toLocaleDateString(\'zh-CN\')}',
    '    function renderRecentInstalls(installs){',
    "        const c=document.getElementById('recent-installs');",
    '        if(!installs||!installs.length){c.innerHTML=\'<div style="text-align:center;color:var(--text-muted);font-size:.9rem;padding:16px 0">暂无安装记录</div>\';return}',
    "        c.innerHTML=installs.map(i=>{",
    "            const loc=[fu(i.city),fu(i.region),fu(i.country)].filter(Boolean).join(', ')||'未知地区';",
    "            const cls=i.active===false?'is-offline':'is-online';",
    "            return '<div class=\"recent-item '+cls+'\"><span class=\"ri-icon\">📍</span><span class=\"ri-location\" title=\"'+loc+'\">'+loc+'</span><span class=\"ri-ip\">'+(i.ip||'')+'</span><span class=\"ri-time\">'+timeAgo(i.time)+'</span></div>'",
    "        }).join('');",
    '    }',
    '',
    '    async function fetchStats(){',
    '        try{',
    "            const r=await(await fetch('/api/stats')).json();",
    '            if(r.code!==0)return;',
    "            document.getElementById('total-calls').textContent=r.data.totalCalls.toLocaleString();",
    '            const t=r.data.lastCallTime;',
    "            if(!t){document.getElementById('last-call').textContent='暂无记录';return}",
    "            const el=document.getElementById('last-call');el.textContent=timeAgo(t);el.title=new Date(t).toLocaleString('zh-CN');",
    '            renderRecentInstalls(r.data.recentInstalls||[]);',
    "        }catch(e){console.error('fetchStats:',e)}",
    '    }',
    '',
    "    document.addEventListener('DOMContentLoaded',()=>{",
    '        setupThemeToggle();',
    '        fetchStats();setInterval(fetchStats,3e4);',
    "        const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('active');ob.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -50px 0px'});",
    "        document.querySelectorAll('.reveal').forEach(el=>ob.observe(el));",
    '    });',
    '</script>',
  ];
  return '\n    ' + lines.join('\n');
}
