// 客户端 JavaScript 模板
// 使用数组 join 方式返回 script 标签，避免模板字符串嵌套问题
export function getClientScript() {
  const lines = [
    '<script>',
    '    const {host,protocol}=window.location;',
    "    let baseUrl='https://brew-cn.mintimate.cn';",
    "    if(host&&!/localhost|127\\.0\\.0\\.1/.test(host)&&protocol!=='file:') baseUrl=protocol+'//'+host;",
    '',
    '    // Update macOS commands',
    "    const macInstall=document.getElementById('install-command-macos');",
    "    const macUninstall=document.getElementById('uninstall-command-macos');",
    "    if(macInstall) macInstall.textContent='/bin/zsh -c \"$(curl -fsSL '+baseUrl+'/install)\"';",
    "    if(macUninstall) macUninstall.textContent='/bin/zsh -c \"$(curl -fsSL '+baseUrl+'/install)\" -- --uninstall';",
    '',
    '    // Update Linux commands',
    "    const linInstall=document.getElementById('install-command-linux');",
    "    const linUninstall=document.getElementById('uninstall-command-linux');",
    "    if(linInstall) linInstall.textContent='/bin/bash -c \"$(curl -fsSL '+baseUrl+'/install)\"';",
    "    if(linUninstall) linUninstall.textContent='/bin/bash -c \"$(curl -fsSL '+baseUrl+'/install)\" -- --uninstall';",
    '',
    '    // OS tab switching',
    "    window.switchOS=function(os){",
    "        document.querySelectorAll('.os-tab').forEach(t=>{t.classList.toggle('active',t.dataset.os===os)});",
    "        document.querySelectorAll('.os-panel').forEach(p=>{p.style.display='none'});",
    "        const panel=document.getElementById('os-'+os);",
    "        if(panel) panel.style.display='block';",
    "    };",
    '',
    '    // Auto-detect OS from User-Agent',
    "    (function(){",
    "        const ua=navigator.userAgent||navigator.platform||'';",
    "        if(/Linux/i.test(ua)&&!/Android/i.test(ua)) switchOS('linux');",
    "    })();",
    '',
    '    function copyCommand(id,btn){',
    '        const text=document.getElementById(id).textContent,orig=btn.textContent;',
    "        const done=()=>{btn.textContent='已复制!';btn.classList.add('copied');setTimeout(()=>{btn.textContent=orig;btn.classList.remove('copied')},2000)};",
    "        if(navigator.clipboard){navigator.clipboard.writeText(text).then(done).catch(done)}else{const t=document.createElement('textarea');t.value=text;t.style.cssText='position:fixed;opacity:0';document.body.appendChild(t);t.select();document.execCommand('copy');document.body.removeChild(t);done()}",
    '    }',
    '',
    '    const THEME_KEY=\'brew-cn-theme\';',
    '    const mediaDark=window.matchMedia(\'(prefers-color-scheme: dark)\');',
    '    const THEME_MODES=[\'light\',\'system\',\'dark\'];',
    '    function getSavedThemeMode(){',
    '        const saved=localStorage.getItem(THEME_KEY);',
    '        return THEME_MODES.includes(saved)?saved:\'system\';',
    '    }',
    '    function resolveTheme(mode){',
    '        return mode===\'system\'?(mediaDark.matches?\'dark\':\'light\'):mode;',
    '    }',
    '    function getModeLabel(mode){',
    '        return mode===\'light\'?\'亮色\':mode===\'dark\'?\'暗色\':\'跟随系统\';',
    '    }',
    '    function applyThemeMode(mode,{persist=false}={}){',
    '        const resolved=resolveTheme(mode);',
    '        document.documentElement.setAttribute(\'data-theme\',resolved);',
    '        const toggle=document.getElementById(\'theme-toggle\');',
    '        if(toggle){',
    '            toggle.dataset.theme=mode;',
    "            toggle.setAttribute(\'aria-label\',\'切换主题（当前\'+getModeLabel(mode)+\'）\');",
    "            toggle.setAttribute(\'title\',\'当前：\'+getModeLabel(mode)+\'（点击切换）\');",
    '        }',
    '        if(persist) localStorage.setItem(THEME_KEY,mode);',
    '    }',
    '    function nextThemeMode(current){',
    '        const idx=THEME_MODES.indexOf(current);',
    '        return THEME_MODES[(idx+1)%THEME_MODES.length];',
    '    }',
    '    function setupThemeToggle(){',
    '        applyThemeMode(getSavedThemeMode());',
    '        const toggle=document.getElementById(\'theme-toggle\');',
    '        if(toggle){',
    '            toggle.addEventListener(\'click\',()=>{',
    '                const current=toggle.dataset.theme||getSavedThemeMode();',
    '                applyThemeMode(nextThemeMode(current),{persist:true});',
    '            });',
    '        }',
    '        const handleChange=()=>{',
    '            if(getSavedThemeMode()===\'system\') applyThemeMode(\'system\');',
    '        };',
    '        if(mediaDark.addEventListener) mediaDark.addEventListener(\'change\',handleChange);',
    '        else if(mediaDark.addListener) mediaDark.addListener(handleChange);',
    '    }',
    '',
    '    const fu=v=>v&&!/unknown/i.test(v)?v:\'\';',
    '    function timeAgo(t){const d=new Date(t),ms=Date.now()-d,m=ms/6e4|0,h=ms/36e5|0,dy=ms/864e5|0;return m<1?\'刚刚\':m<60?m+\'分钟前\':h<24?h+\'小时前\':dy<30?dy+\'天前\':d.toLocaleDateString(\'zh-CN\')}',
    '    const INITIAL_SHOW=10;',
    '    let allInstalls=[];',
    '    function renderRecentInstalls(installs){',
    "        const c=document.getElementById('recent-installs');",
    "        if(!installs||!installs.length){c.innerHTML='<div style=\"text-align:center;color:var(--text-muted);font-size:.9rem;padding:16px 0\">暂无安装记录</div>';return}",
    '        allInstalls=installs;',
    '        renderInstallList(INITIAL_SHOW);',
    '    }',
    '    function renderInstallItem(i){',
    "        const loc=[fu(i.city),fu(i.region),fu(i.country)].filter(Boolean).join(', ')||'未知地区';",
    "        const cls=i.active===false?'is-offline':'is-online';",
    "        return '<div class=\"recent-item '+cls+'\"><span class=\"ri-icon\">📍</span><span class=\"ri-location\" title=\"'+loc+'\">'+loc+'</span><span class=\"ri-ip\">'+(i.ip||'')+'</span><span class=\"ri-time\">'+timeAgo(i.time)+'</span></div>'",
    '    }',
    '    function renderInstallList(count){',
    "        const c=document.getElementById('recent-installs');",
    '        const showing=allInstalls.slice(0,count);',
    "        let html=showing.map(renderInstallItem).join('');",
    "        if(count<allInstalls.length){",
    "            html+='<button class=\"recent-toggle-btn\" onclick=\"expandInstalls()\">展开更多（共 '+allInstalls.length+' 条）</button>'",
    "        }else if(allInstalls.length>INITIAL_SHOW){",
    "            html+='<button class=\"recent-toggle-btn\" onclick=\"collapseInstalls()\">收起</button>'",
    '        }',
    '        c.innerHTML=html;',
    '    }',
    "    window.expandInstalls=function(){renderInstallList(allInstalls.length)};",
    "    window.collapseInstalls=function(){renderInstallList(INITIAL_SHOW);document.getElementById(\"recent-installs\").scrollIntoView({behavior:\"smooth\",block:\"start\"})};",
    '',
    '    async function fetchStats(){',
    '        try{',
    "            const r=await(await fetch('/api/stats')).json();",
    '            if(r.code!==0)return;',
    "            document.getElementById('total-calls').textContent=r.data.totalCalls.toLocaleString();",
    "            const t=r.data.lastCallTime;",
    "            if(!t){document.getElementById('last-call').textContent='暂无记录';return}",
    "            const el=document.getElementById('last-call');el.textContent=timeAgo(t);el.title=new Date(t).toLocaleString('zh-CN');",
    "            renderRecentInstalls(r.data.recentInstalls||[]);",
    "        }catch(e){console.error('fetchStats:',e)}",
    '    }',
    '',
    "    document.addEventListener('DOMContentLoaded',()=>{",
    '        setupThemeToggle();',
    '        fetchStats();setInterval(fetchStats,3e4);',
    "        const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('active');ob.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -50px 0px'});",
    "        document.querySelectorAll('.reveal').forEach(el=>ob.observe(el));",
    '',
    '',
    "        // 隐藏彩蛋：连续输入 brew 显示腾讯云镜像源",
    "        let eggBuf='',eggTimer=null;",
    "        document.addEventListener('keydown',function(e){",
    "            if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;",
    "            clearTimeout(eggTimer);",
    "            eggBuf+=e.key.toLowerCase();",
    "            eggTimer=setTimeout(()=>{eggBuf=''},2000);",
    "            if(eggBuf.includes('brew')){",
    "                eggBuf='';",
    "                const row=document.getElementById('mirror-egg');",
    "                if(row&&!row.classList.contains('egg-show')){",
    "                    row.classList.add('egg-show');",
    "                    row.scrollIntoView({behavior:'smooth',block:'center'});",
    '                }',
    "            }",
    "        });",
    '    });',
    '',
    '    // === AI Chat Agent Client Logic (Tool Calling Thinking Chain) ===',
    '    (function() {',
    '        const toggleBtn = document.getElementById("ai-chat-toggle");',
    '        const closeBtn = document.getElementById("ai-chat-close");',
    '        const chatWindow = document.getElementById("ai-chat-window");',
    '        const chatInput = document.getElementById("chat-input");',
    '        const sendBtn = document.getElementById("chat-send-btn");',
    '        const messagesContainer = document.getElementById("chat-messages");',
    '        const attachmentsEl = document.getElementById("chat-attachments");',
    '        const MAX_PASTED_IMAGES = 3;',
    '        const MAX_PASTED_IMAGE_BYTES = 2 * 1024 * 1024;',
    '        let pendingImages = [];',
    '        let isGenerating = false;',
    '',
    '        if (!toggleBtn) return;',
    '',
    '        function createConversationId() {',
    '            if (window.crypto && typeof window.crypto.randomUUID === "function") return "conv_" + window.crypto.randomUUID().replace(/-/g, "").slice(0, 31);',
    '            return ("conv_" + Date.now().toString(36) + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)).slice(0, 36);',
    '        }',
    '        // One page lifecycle = one chat session; do not persist this in localStorage.',
    '        let convId = createConversationId();',
    '',
    '        // Toggle chat window',
    '        toggleBtn.addEventListener("click", () => {',
    '            if (chatWindow.style.display === "none") {',
    '                chatWindow.style.display = "flex";',
    '                chatInput.focus();',
    '                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '            } else {',
    '                chatWindow.style.display = "none";',
    '            }',
    '        });',
    '',
    '        closeBtn.addEventListener("click", () => {',
    '            chatWindow.style.display = "none";',
    '        });',
    '',
    '        // Input button state',
    '        chatInput.addEventListener("input", () => {',
    '            updateSendState();',
    '        });',
    '',
    '        function updateSendState() {',
    '            sendBtn.disabled = isGenerating || (!chatInput.value.trim() && pendingImages.length === 0);',
    '        }',
    '',
    '        function formatBytes(size) {',
    '            if (size < 1024) return size + " B";',
    '            if (size < 1024 * 1024) return (size / 1024).toFixed(1) + " KB";',
    '            return (size / 1024 / 1024).toFixed(1) + " MB";',
    '        }',
    '',
    '        function renderAttachments() {',
    '            if (!attachmentsEl) return;',
    '            if (!pendingImages.length) { attachmentsEl.innerHTML = ""; return; }',
    '            attachmentsEl.innerHTML = pendingImages.map(function(image, index) {',
    '                return \'<span class="attachment-chip image-chip" title="粘贴的截图"><span>粘贴的截图</span><small>\' + formatBytes(image.size) + \'</small><button type="button" aria-label="移除截图" onclick="removeChatAttachment(\' + index + \')">&times;</button></span>\';',
    '            }).join("");',
    '        }',
    '',
    '        window.removeChatAttachment = function(index) {',
    '            pendingImages.splice(index, 1);',
    '            renderAttachments();',
    '            updateSendState();',
    '        };',
    '',
    '        function readImageAsBase64(file) {',
    '            return new Promise(function(resolve, reject) {',
    '                const reader = new FileReader();',
    '                reader.onload = function() {',
    '                    const value = String(reader.result || "");',
    '                    resolve({ name: file.name, type: file.type || "", size: file.size, base64: value.includes(",") ? value.split(",").pop() : value });',
    '                };',
    '                reader.onerror = function() { reject(reader.error || new Error("读取文件失败")); };',
    '                reader.readAsDataURL(file);',
    '            });',
    '        }',
    '',
    '        chatInput.addEventListener("paste", function(event) {',
    '            const items = Array.from(event.clipboardData && event.clipboardData.items ? event.clipboardData.items : []);',
    '            const images = items.map(function(item) { return item.kind === "file" && item.type.indexOf("image/") === 0 ? item.getAsFile() : null; }).filter(Boolean);',
    '            if (!images.length) return;',
    '            event.preventDefault();',
    '            images.forEach(function(file) {',
    '                if (pendingImages.length >= MAX_PASTED_IMAGES) return;',
    '                if (file.size > MAX_PASTED_IMAGE_BYTES) { alert("截图过大，单张不能超过 2 MB。"); return; }',
    '                pendingImages.push(file);',
    '            });',
    '            renderAttachments();',
    '            updateSendState();',
    '        });',
    '',
    '        // Handle enter key',
    '        chatInput.addEventListener("keydown", (e) => {',
    '            if (e.key === "Enter" && !e.shiftKey) {',
    '                e.preventDefault();',
    '                sendMessage();',
    '            }',
    '        });',
    '',
    '        sendBtn.addEventListener("click", () => sendMessage());',
    '',
    '        window.sendQuickAction = function(text) {',
    '            if (chatWindow.style.display === "none") {',
    '                chatWindow.style.display = "flex";',
    '            }',
    '            sendMessage(text);',
    '        };',
    '',
    '        // Simple markdown parser',
    '        function parseMarkdown(text) {',
    '            const codeBlocks = [];',
    '            const source = String(text || "").replace(/^\\s+/, "").replace(/\\n{3,}/g, "\\n\\n");',
    '            let html = source.replace(/```(\\w*)\\n?([\\s\\S]*?)```/g, function(match, lang, code) {',
    '                const placeholder = "%%CODE_BLOCK_" + codeBlocks.length + "%%";',
    '                const cleanCode = code.replace(/^\\n+|\\n+$/g, "");',
    '                const label = lang || "text";',
    '                codeBlocks.push("<pre class=\\"command-box code-snippet\\" data-lang=\\"" + escapeHtml(label) + "\\"><code>" + escapeHtml(cleanCode) + "</code></pre>");',
    '                return placeholder;',
    '            });',
    '            html = html.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");',
    '            html = html.replace(/`([^`]+)`/g, "<code style=\\"background:rgba(255,140,66,0.1);padding:2px 6px;border-radius:4px;font-family:monospace;color:var(--accent);\\">$1</code>");',
    '            html = html.replace(/\\*\\*([^*]+)\\*\\*/g, "<strong>$1</strong>");',
    '            ',
    '            // Headings',
    '            html = html.replace(/^(#{1,6})\\s+(.+)$/gm, function(match, hashes, content) {',
    '                const level = hashes.length;',
    '                return "<h" + level + ">" + content.trim() + "</h" + level + ">";',
    '            });',
    '            ',
    '            // Lists',
    '            html = html.replace(/^\\s*[-*+]\\s+(.+)$/gm, "<ul><li>$1</li></ul>");',
    '            html = html.replace(/<\\/ul>\\s*<ul>/g, "");',
    '            html = html.replace(/^\\s*(\\d+)\\.\\s+(.+)$/gm, "<ol><li value=\\"$1\\">$2</li></ol>");',
    '            html = html.replace(/<\\/ol>\\s*<ol>/g, "");',
    '            ',
    '            html = html.replace(/\\n/g, "<br>");',
    '            ',
    '            // Clean up extra line breaks around lists and headings',
    '            html = html.replace(/<(h[1-6]|ul|ol|li|pre|code)([^>]*)><br>/g, "<$1$2>");',
    '            html = html.replace(/<br><\\/(h[1-6]|ul|ol|li|pre|code)>/g, "</$1>");',
    '            html = html.replace(/<\\/(h[1-6]|ul|ol|pre|code)><br>/g, "</$1>");',
    '            html = html.replace(/^(<br>)+/g, "");',
    '            html = html.replace(/(<br>\\s*){3,}/g, "<br><br>");',
    '            codeBlocks.forEach(function(block, index) {',
    '                html = html.replace("%%CODE_BLOCK_" + index + "%%", block);',
    '            });',
    '            return html;',
    '        }',
    '',
    '        // ═══ Agent 消息结构常量 ═══',
    '        const AGENT_MSG = {',
    '            ROW_CLS: "agent-message-row",',
    '            AVATAR_CLS: "agent-avatar",',
    '            BUBBLE_CLS: "agent-bubble",',
    '            LOGS_FLOW_CLS: "agent-logs-flow",',
    '            TEXT_CONTENT_CLS: "agent-text-content",',
    '        };',
    '',
    '        let activeAssistantMessage = null;',
    '        let activeTextContent = null;',
    '        let activeStatusElement = null;',
    '        let statusTimer = null;',
    '        let currentToolName = "";',
    '        let activeToolCards = new Map();',
    '        let toolStepCounter = 0;',
    '        let diagnosticState = { analysis: null, fix: "" };',
    '',
    '        /** 创建 Agent 回复骨架（avatar + bubble + 推理链容器） */',
    '        function createAgentSkeleton() {',
    '            const row = document.createElement("div");',
    '            row.className = AGENT_MSG.ROW_CLS;',
    '            row.innerHTML =',
    '                \'<div class="\' + AGENT_MSG.AVATAR_CLS + \'">\' +',
    '                \'<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\' +',
    '                \'<path d="M6.5 9.5 v8.5 a2 2 0 0 0 2 2 h3 a2 2 0 0 0 2 -2 v-8.5"/>\' +',
    '                \'<path d="M13.5 11.5 h2 a1.5 1.5 0 0 1 1.5 1.5 v3 a1.5 1.5 0 0 1 -1.5 1.5 h-2"/>\' +',
    '                \'<path d="M18 3 Q18 7 22 7 Q18 7 18 11 Q18 7 14 7 Q18 7 18 3 Z" fill="currentColor" stroke="none" opacity="0.8"/>\' +',
    '                \'</svg></div>\' +',
    '                \'<div class="\' + AGENT_MSG.BUBBLE_CLS + \'"></div>\';',
    '            messagesContainer.appendChild(row);',
    '            const bubble = row.querySelector("." + AGENT_MSG.BUBBLE_CLS);',
    '',
    '            // 推理链容器（始终创建，可折叠）',
    '            const tw = document.createElement("div");',
    '            tw.className = "thinking-wrapper";',
    '            tw.innerHTML =',
    '                \'<div class="thinking-header">\' +',
    '                \'<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"/></svg>\' +',
    '                \'<span>Agent 推理链</span></div>\' +',
    '                \'<div class="thinking-content" style="display:none"></div>\' +',
    '                \'<div class="thinking-body"></div>\';',
    '            bubble.appendChild(tw);',
    '',
    '            const thinkingBody = tw.querySelector(".thinking-body");',
    '            const thinkingContentEl = tw.querySelector(".thinking-content");',
    '',
    '            // 点击折叠/展开',
    '            tw.querySelector(".thinking-header").addEventListener("click", function() {',
    '                var isCollapsed = tw.classList.toggle("collapsed");',
    '                var svg = tw.querySelector(".thinking-header svg");',
    '                svg.style.transform = isCollapsed ? "rotate(-90deg)" : "";',
    '            });',
    '',
    '            // 最终回答文本区',
    '            const textContent = document.createElement("div");',
    '            textContent.className = AGENT_MSG.TEXT_CONTENT_CLS;',
    '            bubble.appendChild(textContent);',
    '            ',
    '            return { row, bubble, thinkingWrapper: tw, thinkingBody, thinkingContent: thinkingContentEl, textContent };',
    '        }',
    '',
    '        // ── Thinking / Reasoning Block（LLM 推理文本追加到推理链内） ───────────',
    '        var thinkingText = "";',
    '',
    '        function handleThinkingEvent(skeleton, content) {',
    '            if (!skeleton || !skeleton.thinkingWrapper) return;',
    '            thinkingText += String(content || "");',
    '            var tc = skeleton.thinkingContent;',
    '            tc.innerHTML = parseMarkdown(normalizeThinkingText(thinkingText));',
    '            tc.style.display = "";',
    '            tc.scrollTop = tc.scrollHeight;',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '        }',
    '',
    '        function collapseThinkingBody(skeleton) {',
    '            if (!skeleton || !skeleton.thinkingBody) return;',
    '            skeleton.thinkingWrapper.classList.remove("collapsed");',
    '            skeleton.thinkingBody.classList.remove("collapsed");',
    '            var svg = skeleton.thinkingWrapper.querySelector(".thinking-header svg");',
    '            if (svg) svg.style.transform = "";',
    '        }',
    '',
    '        function resetThinking() { thinkingText = ""; toolStepCounter = 0; }',
    '',
    '        function normalizeThinkingText(content) {',
    '            return String(content || "").replace(/\\r\\n/g, "\\n");',
    '        }',
    '',
    '        function formatEventClock() {',
    '            var now = new Date();',
    '            var hh = String(now.getHours()).padStart(2, "0");',
    '            var mm = String(now.getMinutes()).padStart(2, "0");',
    '            var ss = String(now.getSeconds()).padStart(2, "0");',
    '            return hh + ":" + mm + ":" + ss;',
    '        }',
    '',
    '        function formatToolArguments(rawArgs) {',
    '            if (rawArgs === null || rawArgs === undefined || rawArgs === "") return "{}";',
    '            if (typeof rawArgs === "object") return JSON.stringify(rawArgs, null, 2);',
    '            var text = String(rawArgs);',
    '            try {',
    '                return JSON.stringify(JSON.parse(text), null, 2);',
    '            } catch (e) {',
    '                return text;',
    '            }',
    '        }',
    '',
    '        // ── Tool Call 卡片（✅ 工具执行成功 + 结果框） ─────────────────────',
    '        function handleToolCallEvent(skeleton, toolName, toolArgs) {',
    '            var body = skeleton.thinkingBody;',
    '            if (!body) return null;',
    '            toolStepCounter += 1;',
    '            var blockId = "tool-" + toolName.replace(/:/g, "-") + "-" + Date.now();',
    '            var block = document.createElement("div");',
    '            block.className = "tool-call-log";',
    '            block.id = blockId;',
    '            block.dataset.toolName = toolName;',
    '            block.dataset.toolStep = String(toolStepCounter);',
    '            var formattedArgs = formatToolArguments(toolArgs);',
    '            var showArgs = toolName !== "intent_classify" && formattedArgs !== "{}";',
    '            block.innerHTML =',
    '                \'<div class="tool-call-header running">\' +',
    '                \'<svg class="spin-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><path d="M12 2v4"/></svg>\' +',
    '                \'<span>步骤 \' + toolStepCounter + \' · 正在调用工具: \' + escapeHtml(toolLabel(toolName)) + \'...</span><span class="tool-time">\' + formatEventClock() + \'</span></div>\';',
    '            if (showArgs) {',
    '                block.innerHTML += \'<details class="tool-call-args"><summary>工具入参</summary><pre class="tool-call-output tool-call-args-code">\' + escapeHtml(formattedArgs) + \'</pre></details>\';',
    '            }',
    '            body.appendChild(block);',
    '            activeToolCards.set(blockId, { el: block, name: toolName, done: false });',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '            return blockId;',
    '        }',
    '',
    '        function handleToolResultEvent(skeleton, toolName, resultText, partial) {',
    '            var body = skeleton ? skeleton.thinkingBody : null;',
    '            if (!body) return;',
    '            var items = body.querySelectorAll(".tool-call-log");',
    '            var matchedBlock = null;',
    '            for (var i = items.length - 1; i >= 0; i--) {',
    '                var header = items[i].querySelector(".tool-call-header");',
    '                if (header && header.classList.contains("running") && items[i].dataset.toolName === toolName) {',
    '                    matchedBlock = items[i]; break;',
    '                }',
    '            }',
    '            if (matchedBlock) {',
    '                var header = matchedBlock.querySelector(".tool-call-header");',
    '                var stepText = matchedBlock.dataset.toolStep ? ("步骤 " + matchedBlock.dataset.toolStep + " · ") : "";',
    '                if (partial) {',
    '                    header.className = "tool-call-header running";',
    '                    header.innerHTML =',
    '                        \'<svg class="spin-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><path d="M12 2v4"/></svg>\' +',
    '                        \'<span>\' + stepText + \'工具执行中: \' + escapeHtml(toolLabel(toolName)) + \'</span><span class="tool-time">\' + formatEventClock() + \'</span>\';',
    '                } else {',
    '                    header.className = "tool-call-header success";',
    '                    header.innerHTML =',
    '                        \'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"/></svg>\' +',
    '                        \'<span>\' + stepText + \'工具执行成功: \' + escapeHtml(toolLabel(toolName)) + \'</span><span class="tool-time">\' + formatEventClock() + \'</span>\';',
    '                }',
    '                if (resultText) {',
    '                    var out = matchedBlock.querySelector(".tool-call-output.result");',
    '                    if (!out) {',
    '                        out = document.createElement("div");',
    '                        out.className = "tool-call-output result compact-summary";',
    '                        matchedBlock.appendChild(out);',
    '                    }',
    '                    out.textContent = resultText;',
    '                }',
    '                var cardId = matchedBlock.id;',
    '                if (!partial && activeToolCards.has(cardId)) activeToolCards.get(cardId).done = true;',
    '            } else {',
    '                var block = document.createElement("div"); block.className = "tool-call-log"; block.dataset.toolName = toolName;',
    '                block.innerHTML = \'<div class="tool-call-header success">\' +',
    '                    \'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"/></svg>\' +',
    '                    \'<span>工具执行成功: \' + escapeHtml(toolName) + \'</span><span class="tool-time">\' + formatEventClock() + \'</span></div>\';',
    '                if (resultText) block.innerHTML += \'<div class="tool-call-output result compact-summary">\' + escapeHtml(resultText) + "</div>";',
    '                body.appendChild(block);',
    '            }',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '        }',
    '',
    '        /** 为特殊工具渲染富内容（diagnose 表格 / analyze+fix 问题卡片）到已创建的工具卡片中 */',
    '        function renderRichToolContent(skeleton, toolName, content, partial) {',
    '            var body = skeleton ? skeleton.thinkingBody : null;',
    '            if (!body) return;',
    '            var items = body.querySelectorAll(".tool-call-log");',
    '            var targetCard = null;',
    '            for (var i = items.length - 1; i >= 0; i--) { if (items[i].dataset.toolName === toolName) { targetCard = items[i]; break; } }',
    '            if (!targetCard) return;',
    '            var existingRichBody = targetCard.querySelector(".tool-rich-body");',
    '            if (existingRichBody) existingRichBody.remove();',
    '            var richBody = document.createElement("div"); richBody.className = "tool-rich-body"; targetCard.appendChild(richBody);',
    '            if (toolName === "diagnose" || toolName === "mirror_probe_deep") renderDiagnoseRichContent(richBody, parseJsonPayload(content), !!partial);',
    '            else if (toolName === "analyze") { diagnosticState.analysis = parseJsonPayload(content); renderDiagnosticRichContent(richBody); }',
    '            else if (toolName === "fix") { diagnosticState.fix = String(content || ""); renderDiagnosticRichContent(richBody); }',
    '            else { richBody.innerHTML = \'<pre class="tool-raw-output">\' + escapeHtml(String(content || "")) + \'</pre>\'; }',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '        }',
    '',
    '        // ── 特殊工具：诊断（镜像检测表格） ──────────────────────────────',
    '        function renderDiagnoseRichContent(container, data, partial) {',
    '            var report = data && Array.isArray(data.report) ? data.report : [];',
    '            if (!report.length) {',
    '                container.innerHTML = \'<div class="tool-empty">正在等待镜像响应...</div>\';',
    '                return;',
    '            }',
    '            function timingLabel(label, value) { return typeof value === "number" ? label + value + "ms" : ""; }',
    '            var rows = report.map(function(r) {',
    '                var latency = typeof r.latency_ms === "number" && r.latency_ms < 9999 ? r.latency_ms + " ms" : "-";',
    '                var shortHash = r.commit_hash ? escapeHtml(String(r.commit_hash).slice(0, 10)) : "-";',
    '                var method = r.method === "sandbox_deep" ? "\\u6c99\\u7bb1\\u6df1\\u6d4b" : r.method === "sandbox" ? "\\u6c99\\u7bb1" : "\\u8fb9\\u7f18";',
    '                var note = r.network_note || (r.sync_status === "network_restricted" ? "EdgeOne 沙箱无法访问 GitHub，非官方源故障" : "");',
    '                var details = [note, method, timingLabel("DNS ", r.dns_ms), timingLabel("TCP ", r.tcp_ms), timingLabel("TLS ", r.tls_ms), timingLabel("Git ", r.git_ms), r.ip ? "IP " + r.ip : ""].filter(Boolean).join(" · ");',
    '                return \'<div class="tool-row">\' +',
    '                    \'<span class="tool-main" title="\' + escapeHtml(details || r.name || "") + \'"><strong>\' + escapeHtml(r.name || "Unknown") + \'</strong><span>\' + escapeHtml(details) + \'</span></span>\' +',
    '                    \'<span class="tool-mono">\' + latency + \'</span>\' +',
    '                    statusBadge(r.sync_status, !!r.error && r.sync_status !== "network_restricted") +',
    '                    \'<span class="tool-mono tool-hide-sm">\' + (r.http_status || 0) + \'</span>\' +',
    '                    \'<span class="tool-mono tool-hide-sm">\' + shortHash + \'</span>\' +',
    '                \'</div>\';',
    '            }).join("");',
    '            container.innerHTML =',
    '                \'<div class="tool-grid-head"><span>镜像源</span><span>延迟</span><span>状态</span><span class="tool-hide-sm">HTTP</span><span class="tool-hide-sm">Commit</span></div>\' +',
    '                rows +',
    '                (partial ? "" : \'<button class="tool-copy-btn" onclick="copyToolCardText(this)">复制报告</button>\');',
    '            container._sourceData = data;',
    '        }',
    '',
    '        // ── 特殊工具：环境诊断（问题卡片） ──────────────────────────────',
    '        function renderDiagnosticRichContent(container) {',
    '            var data = diagnosticState.analysis;',
    '            var issues = data && Array.isArray(data.issues) ? data.issues : [];',
    '            var parts = [];',
    '            if (!data) {',
    '                parts.push(\'<div class="tool-empty">正在分析环境信息...</div>\');',
    '            } else if (!issues.length) {',
    '                parts.push(\'<div class="diagnostic-section"><div class="diagnostic-section-title">结果</div><div class="tool-empty">未发现明显配置问题。</div></div>\');',
    '            } else {',
    '                var issueHtml = issues.map(function(issue) {',
    '                    var cls = issue.severity === "error" ? "bad" : issue.severity === "warning" ? "warn" : "info";',
    '                    return \'<div class="issue-card">\' +',
    '                        \'<div class="issue-title"><span class="tool-badge \' + cls + \'">\' + escapeHtml(issue.severity || "info") + \'</span><strong>\' + escapeHtml(issue.title || "问题") + \'</strong></div>\' +',
    '                        \'<p>\' + escapeHtml(issue.message || "") + \'</p><p class="issue-suggest">\' + parseMarkdown(issue.suggestion || "") + \'</p>\' +',
    '                    \'</div>\';',
    '                }).join("");',
    '                parts.push(\'<div class="diagnostic-section"><div class="diagnostic-section-title">问题</div>\' + issueHtml + \'</div>\');',
    '            }',
    '            if (diagnosticState.fix) {',
    '                parts.push(\'<div class="diagnostic-section"><div class="diagnostic-section-title">修复命令</div><pre class="command-box tool-command-box"><code>\' + escapeHtml(diagnosticState.fix) + \'</code></pre></div><button class="tool-copy-btn" onclick="copyToolCardText(this)">复制修复命令</button>\');',
    '            } else if (data) {',
    '                parts.push(\'<pre class="tool-raw-output">\' + escapeHtml(JSON.stringify(data, null, 2)) + \'</pre><button class="tool-copy-btn" onclick="copyToolCardText(this)">复制分析结果</button>\');',
    '            }',
    '            container.innerHTML = parts.join("");',
    '        }',
    '',
    '        function setStatus(text, skeleton) {',
    '            try {',
    '                if (statusTimer) { clearTimeout(statusTimer); statusTimer = null; }',
    '                if (activeStatusElement && activeStatusElement.isConnected) { activeStatusElement.remove(); }',
    '                activeStatusElement = null;',
    '                if (!text) return;',
    '                activeStatusElement = document.createElement("div");',
    '                activeStatusElement.className = "status-hint";',
    '                var spinSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");',
    "                spinSvg.setAttribute('class', 'spin-svg'); spinSvg.setAttribute('viewBox', '0 0 24 24');",
    "                spinSvg.setAttribute('fill', 'none'); spinSvg.setAttribute('stroke', 'currentColor'); spinSvg.setAttribute('stroke-width', '2.5');",
    '                spinSvg.innerHTML = \'<circle cx="12" cy="12" r="10"/><path d="M12 2v4"/>\';',
    '                var sp = document.createElement("span"); sp.textContent = text;',
    '                activeStatusElement.appendChild(spinSvg);',
    '                activeStatusElement.appendChild(sp);',
    '                var target = (skeleton && skeleton.thinkingBody) ? skeleton.thinkingBody : messagesContainer;',
    '                target.appendChild(activeStatusElement);',
    '                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '            } catch (e) {',
    '                console.warn("setStatus failed:", e);',
    '            }',
    '        }',
    '',
    '        function escapeHtml(text) {',
    '            var div = document.createElement("div");',
    '            div.textContent = text;',
    '            return div.innerHTML;',
    '        }',
    '',
    '        function parseJsonPayload(value) {',
    '            if (!value) return null;',
    '            if (typeof value === "object") return value;',
    '            try { return JSON.parse(value); } catch(e) { return null; }',
    '        }',
    '',
    '        function toolLabel(name) {',
    '            return name === "intent_classify" ? "意图识别" : name === "diagnose" || name === "mirror_probe_deep" ? "在线镜像深度检测" : name === "formula_check" ? "软件包索引查询" : name === "analyze" || name === "fix" ? "环境诊断" : name;',
    '        }',
    '',
    '        function statusBadge(status, hasError) {',
    '            if (status === "network_restricted") return \'<span class="tool-badge warn">沙箱受限</span>\';',
    '            if (hasError || status === "failed") return \'<span class="tool-badge bad">失败</span>\';',
    '            if (status === "lagging") return \'<span class="tool-badge warn">延迟同步</span>\';',
    '            if (status === "upstream") return \'<span class="tool-badge info">官方源</span>\';',
    '            return \'<span class="tool-badge ok">同步正常</span>\';',
    '        }',
    '',
    '        /** 复制工具卡片中的数据 */',
    '        window.copyToolCardText = function(btn) {',
    '            var card = btn.closest(".tool-call-log");',
    '            if (!card) { var panel = btn.closest(".tool-panel"); if (panel) card = panel; }',
    '            if (!card) return;',
    '            var sourceEl = card.querySelector(".tool-raw-output") || card.querySelector(".tool-command-box") || card.querySelector(".tool-call-output");',
    '            var text = sourceEl ? sourceEl.textContent : "";',
    '            // 如果没有文本元素但有存储的数据（诊断报告）',
    '            if (!text && card._sourceData) { text = JSON.stringify(card._sourceData, null, 2); }',
    '            if (!text) return;',
    '            var done = function() { var old = btn.textContent; btn.textContent = "已复制"; setTimeout(function(){ btn.textContent = old; }, 1600); };',
    '            if (navigator.clipboard) navigator.clipboard.writeText(text).then(done).catch(done);',
    '            else { var t = document.createElement("textarea"); t.value = text; t.style.cssText = "position:fixed;opacity:0"; document.body.appendChild(t); t.select(); document.execCommand("copy"); document.body.removeChild(t); done(); }',
    '        };',
    '',
    '        async function sendMessage(overrideText) {',
    '            if (isGenerating) return;',
    '            var imagesToSend = pendingImages.slice();',
    '            var rawText = (overrideText || chatInput.value).trim();',
    '            var text = rawText || (imagesToSend.length ? "请根据我粘贴的终端截图判断 Homebrew/brew 问题" : "");',
    '            if (!text) return;',
    '',
    '            isGenerating = true;',
    '            chatInput.disabled = true;',
    '            sendBtn.disabled = true;',
    '            document.querySelectorAll(".quick-actions button").forEach(function(btn) { btn.disabled = true; });',
    '',
    '            if (!overrideText) {',
    '                chatInput.value = "";',
    '            }',
    '            pendingImages = [];',
    '            renderAttachments();',
    '',
    '            // Append user message',
    '            var userMsgDiv = document.createElement("div");',
    '            userMsgDiv.className = "message user";',
    '            var attachmentHtml = imagesToSend.length ? \'<div class="message-attachments">\' + imagesToSend.map(function() { return \'<span>粘贴的截图</span>\'; }).join("") + \'</div>\' : "";',
    '            userMsgDiv.innerHTML = escapeHtml(text) + attachmentHtml;',
    '            messagesContainer.appendChild(userMsgDiv);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '',
    '            // 创建 Agent 回复骨架（avatar + 推理链容器 + 文本区）',
    '            var skeleton = createAgentSkeleton();',
    '            activeAssistantMessage = skeleton.row;',
    '            activeTextContent = skeleton.textContent;',
    '            activeToolCards.clear();',
    '            resetThinking();',
    '            diagnosticState = { analysis: null, fix: "" };',
    '            var responseText = "";',
    '            var lastEventTime = Date.now();',
    '            var requestTimeout = null;',
    '            setStatus("请求已发送，等待服务响应...", skeleton);',
    '            ',
    '            try {',
    '                var images = await Promise.all(imagesToSend.map(readImageAsBase64));',
    '                var response = await fetch("/chat", {',
    '                    method: "POST",',
    '                    headers: {',
    '                        "Content-Type": "application/json",',
    '                        "makers-conversation-id": convId',
    '                    },',
    '                    body: JSON.stringify({ message: text, images: images })',
    '                });',
    '',
    '                if (!response.ok) {',
    '                    var errorText = "";',
    '                    try {',
    '                        var errorPayload = await response.json();',
    '                        errorText = errorPayload && (errorPayload.error || errorPayload.message) ? (errorPayload.error || errorPayload.message) : "";',
    '                    } catch (e) {',
    '                        try { errorText = await response.text(); } catch (_) {}',
    '                    }',
    '                    throw new Error(errorText || ("HTTP " + response.status));',
    '                }',
    '                setStatus("服务已连接，等待模型首条输出...", skeleton);',
    '',
    '                var reader = response.body.getReader();',
    '                var decoder = new TextDecoder();',
    '                var buffer = "";',
    '',
    '                requestTimeout = setInterval(function() {',
    '                    var idleMs = Date.now() - lastEventTime;',
    '                    if (idleMs > 12000) {',
    '                        setStatus("仍在等待模型输出，网络可能较慢...", skeleton);',
    '                    }',
    '                    if (idleMs > 25000) {',
    '                        clearInterval(requestTimeout); requestTimeout = null;',
    '                        reader.cancel();',
    '                        setStatus(null);',
    '                        activeTextContent.innerHTML = "<span style=\'color:red\'>请求超时，请重试。</span>";',
    '                    }',
    '                }, 1000);',
    '',
    '                while (true) {',
    '                    var _ref = await reader.read();',
    '                    var done = _ref.done;',
    '                    var value = _ref.value;',
    '                    if (done) break;',
    '                    lastEventTime = Date.now();',
    '',
    '                    buffer += decoder.decode(value, { stream: true });',
    '                    var lines = buffer.split("\\n");',
    '                    buffer = lines.pop() || "";',
    '                    for (var li = 0; li < lines.length; li++) {',
    '                        var trimmed = lines[li].trim();',
    '                        if (!trimmed || !trimmed.startsWith("data:")) continue;',
    '                        var payloadStr = trimmed.slice(5).trim();',
    '                        if (payloadStr === "[DONE]") {',
    '                            setStatus(null);',
    '                            continue;',
    '                        }',
    '',
    '                        try {',
    '                            var event = JSON.parse(payloadStr);',
    '                            ',
    '                            if (event.type === "ping") {',
    '                                continue;',
    '                            }',
    '                            ',
    '                            if (event.type === "thinking" || event.type === "reasoning") {',
    '                                if (event.content === null || event.content === undefined) continue;',
    '                                var rawThinkingContent = String(event.content);',
    '                                var contentTrimmed = rawThinkingContent.trim();',
    '                                var isPlaceholder = event.type === "thinking" && (contentTrimmed === "\\u5df2\\u6536\\u5230\\u95ee\\u9898\\uff0c\\u6b63\\u5728\\u8fdb\\u884c\\u610f\\u56fe\\u8bc6\\u522b…" || contentTrimmed === "\\u6b63\\u5728\\u5206\\u6790\\u4f60\\u7684\\u95ee\\u9898…" || contentTrimmed === "\\u5df2\\u8bc6\\u522b\\u4e3a\\u975e Homebrew \\u76f8\\u5173\\u95ee\\u9898\\u3002");',
    '                                if (isPlaceholder) {',
    '                                    setStatus(contentTrimmed, skeleton);',
    '                                } else if (contentTrimmed || event.type === "reasoning") {',
    '                                    setStatus(null, skeleton);',
    '                                    handleThinkingEvent(skeleton, rawThinkingContent);',
    '                                }',
    '                                currentToolName = "";',
    '                            } else if (event.type === "tool_call") {',
    '                                collapseThinkingBody(skeleton);',
    '                                currentToolName = event.name;',
    '                                handleToolCallEvent(skeleton, event.name, event.arguments);',
    '                                setStatus("[\\u5de5\\u5177\\u8c03\\u7528] " + toolLabel(event.name), skeleton);',
    '                            } else if (event.type === "tool_result") {',
    '                                var resultName = event.name || currentToolName || "tool";',
    '                                // 先生成摘要文本写入 output 框',
    '                                var summaryText = formatToolSummary(resultName, event.content);',
    '                                handleToolResultEvent(skeleton, resultName, summaryText, !!event.partial);',
    '                                // 对特殊工具追加富内容渲染',
    '                                if (resultName === "diagnose" || resultName === "mirror_probe_deep" || resultName === "analyze" || resultName === "fix" || resultName === "formula_check") { renderRichToolContent(skeleton, resultName, event.content, event.partial); }',
    '                                if (!event.partial) {',
    '                                    setStatus(null, skeleton);',
    '                                    currentToolName = "";',
    '                                }',
    '                            } else if (event.type === "ai_response") {',
    '                                collapseThinkingBody(skeleton);',
    '                                if (event.content && (event.content.includes("\\u6b63\\u5728\\u4e3a\\u4f60\\u8fd0\\u884c\\u5728\\u7ebf\\u955c\\u68c0\\u6d4b") || event.content.includes("\\u6b63\\u5728\\u8fd0\\u884c\\u5728\\u7ebf\\u955c\\u68c0\\u6d4b") || event.content.includes("\\u68c0\\u6d4b"))) {',
    '                                    continue;',
    '                                }',
    '                                responseText += event.content;',
    '                                activeTextContent.innerHTML = parseMarkdown(responseText);',
    '                                activeTextContent.style.display = "";',
    '                                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '                            } else if (event.type === "error_message") {',
    '                                setStatus(null, skeleton);',
    '                                var errorDiv = document.createElement("div"); errorDiv.className = "tool-call-log";',
    '                                errorDiv.innerHTML = \'<div class="tool-call-header" style="color:#ef4444">\' + \'<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><path d="M15 9l-6 6M9 9l6 6"/></svg>\' + \'<span>错误: \' + escapeHtml(event.content) + "</span></div>";',
    '                                if (skeleton && skeleton.thinkingBody) skeleton.thinkingBody.appendChild(errorDiv); else messagesContainer.appendChild(errorDiv);',
    '                                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '                            }',
    '                        } catch (e) {',
    '                            console.error("Error parsing SSE line:", e);',
    '                        }',
    '                    }',
    '                }',
    '                ',
    '                setStatus(null, skeleton);',
    '                collapseThinkingBody(skeleton);',
    '',
    '            } catch (err) {',
    '                if (requestTimeout) { clearInterval(requestTimeout); requestTimeout = null; }',
    '                setStatus(null, skeleton);',
    '                if (activeTextContent) activeTextContent.innerHTML = \'<span style="color:red">\' + escapeHtml(err && err.message ? err.message : "连接失败，请重试。") + \'</span>\';',
    '                console.error("Chat error:", err);',
    '            } finally {',
    '                if (requestTimeout) { clearInterval(requestTimeout); requestTimeout = null; }',
    '                isGenerating = false;',
    '                chatInput.disabled = false;',
    '                updateSendState();',
    '                document.querySelectorAll(".quick-actions button").forEach(function(btn) { btn.disabled = false; });',
    '            }',
    '        }',
    '',
    '        /** 将工具结果格式化为简短摘要文本（显示在灰色 output 框中） */',
    '        function formatToolSummary(toolName, rawContent) {',
    '            if (!rawContent) return "";',
    '            if (toolName === "intent_classify") {',
    '                try {',
    '                    var intent = typeof rawContent === "string" ? JSON.parse(rawContent) : rawContent;',
    '                    var scope = intent.is_homebrew_related ? "Homebrew 相关" : "非 Homebrew 相关";',
    '                    var sandbox = intent.needs_sandbox ? "需要沙盒" : "不需要沙盒";',
    '                    var routeLabels = { model_identity: "\\u8eab\\u4efd\\u8bf4\\u660e", restore_official: "\\u6062\\u590d\\u5b98\\u65b9\\u6e90", mirror_probe_deep: "\\u955c\\u50cf\\u6df1\\u5ea6\\u68c0\\u6d4b", formula_check: "\\u8f6f\\u4ef6\\u5305\\u7d22\\u5f15\\u67e5\\u8be2", brew_missing: "brew PATH \\u6392\\u67e5", analysis_fix: "\\u7ec8\\u7aef\\u65e5\\u5fd7\\u5206\\u6790", general_homebrew: "\\u5e38\\u89c4 Homebrew \\u56de\\u7b54", reject: "\\u62d2\\u7b54" };',
    '                    return scope + "\\uff0c" + sandbox + "\\uff0c下一步: " + (routeLabels[intent.route] || intent.route) + "\\u3002";',
    '                } catch(e) { return String(rawContent).slice(0, 200); }',
    '            }',
    '            if (toolName === "diagnose" || toolName === "mirror_probe_deep") {',
    '                try {',
    '                    var data = typeof rawContent === "string" ? JSON.parse(rawContent) : rawContent;',
    '                    var report = data.report || [];',
    '                    var availableMirrors = report.filter(function(r) { return !r.error && r.http_status >= 200 && r.http_status < 400 && r.name !== "Official (\\u5b98\\u65b9\\u6e90)"; });',
    '                    var officialRestricted = report.some(function(r) { return r.sync_status === "network_restricted"; });',
    '                    var best = availableMirrors.slice().sort(function(a,b) { return a.latency_ms - b.latency_ms; })[0];',
    '                    var parts = ["\\u68c0\\u6d4b\\u5230 " + report.length + " \\u4e2a\\u6e90"];',
    '                    if (availableMirrors.length > 0) parts.push(availableMirrors.length + " \\u4e2a\\u955c\\u50cf\\u53ef\\u7528");',
    '                    if (officialRestricted) parts.push("\\u5b98\\u65b9\\u6e90\\u4e3a\\u6c99\\u7bb1\\u7f51\\u7edc\\u53d7\\u9650");',
    '                    if (best) parts.push("\\u6700\\u4f73: " + best.name + " (" + best.latency_ms + "ms)");',
    '                    if (data.duration_ms) parts.push("\\u8017\\u65f6: " + (data.duration_ms / 1000).toFixed(1) + "s");',
    '                    return parts.join("\\uff0c ") + "\\u3002";',
    '                } catch(e) { return String(rawContent).slice(0, 200); }',
    '            }',
    '            if (toolName === "analyze") {',
    '                try {',
    '                    var d = typeof rawContent === "string" ? JSON.parse(rawContent) : rawContent;',
    '                    var issues = d.issues || [];',
    '                    if (!issues.length) return "\\u672a\\u53d1\\u73b0\\u663e\\u8457\\u914d\\u7f6e\\u95ee\\u9898\\u3002";',
    '                    return "\\u53d1\\u73b0 " + issues.length + " \\u4e2a\\u95ee\\u9898\\uff08" + issues.filter(function(i){return i.severity==="error"}).length + " \\u4e2a\\u9519\\u8bef/" + issues.filter(function(i){return i.severity==="warning"}).length + " \\u4e2a\\u8b66\\u544a\\uff09\\u3002";',
    '                } catch(e) { return String(rawContent).slice(0, 200); }',
    '            }',
    '            if (toolName === "fix") {',
    '                return "\\u5df2\\u751f\\u6210\\u4fee\\u590d\\u547d\\u4ee4\\u3002";',
    '            }',
    '            if (toolName === "formula_check") {',
    '                try {',
    '                    var f = typeof rawContent === "string" ? JSON.parse(rawContent) : rawContent;',
    '                    if (f.partial || f.source === "pending") return "\\u6b63\\u5728\\u67e5\\u8be2 Homebrew JSON \\u7d22\\u5f15: " + (f.query || "") + "...";',
    '                    var best = f.exact || (f.candidates || [])[0];',
    '                    if (!best) return "\\u672a\\u5728 Homebrew JSON \\u7d22\\u5f15\\u4e2d\\u627e\\u5230\\u660e\\u786e\\u5339\\u914d\\u3002";',
    '                    return "\\u547d\\u4e2d " + best.type + ": " + best.token + "\\uff0c\\u547d\\u4ee4: " + best.install_command;',
    '                } catch(e) { return String(rawContent).slice(0, 200); }',
    '            }',
    '            // 默认截断',
    '            var s = String(rawContent);',
    '            return s.length > 200 ? s.slice(0, 200) + "..." : s;',
    '        }',
    '    })();',
    '</script>',
  ];
  return '\n    ' + lines.join('\n');
}
