// 客户端逻辑沿用线上交互，任务入口与镜像配置引导在此合入。
// 逐行字符串避免模板字符串与客户端代码相互转义。
import { getTroubleshootingClientLines } from './troubleshooting.js';
import { getConversationClientLines } from './conversation.js';

export function getClientScript() {
  const lines = [
    "<script>",
    "    const UI_ICONS = {\"Assistant\":\"<svg class=\\\"icon assistant-mark \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" viewBox=\\\"0 0 24 24\\\" width=\\\"24\\\" height=\\\"24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"2\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\" focusable=\\\"false\\\">\\n    <path d=\\\"M6.5 9.5 v8.5 a2 2 0 0 0 2 2 h3 a2 2 0 0 0 2 -2 v-8.5\\\"/>\\n    <path d=\\\"M13.5 11.5 h2 a1.5 1.5 0 0 1 1.5 1.5 v3 a1.5 1.5 0 0 1 -1.5 1.5 h-2\\\"/>\\n    <path d=\\\"M18 3 Q18 7 22 7 Q18 7 18 11 Q18 7 14 7 Q18 7 18 3 Z\\\" fill=\\\"currentColor\\\" stroke=\\\"none\\\" opacity=\\\"0.8\\\"/>\\n  </svg>\",\"Copy\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><rect width=\\\"14\\\" height=\\\"14\\\" x=\\\"8\\\" y=\\\"8\\\" rx=\\\"2\\\" ry=\\\"2\\\"></rect><path d=\\\"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2\\\"></path></svg>\",\"Check\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M20 6 9 17l-5-5\\\"></path></svg>\",\"X\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M18 6 6 18\\\"></path><path d=\\\"m6 6 12 12\\\"></path></svg>\",\"ArrowUp\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"m5 12 7-7 7 7\\\"></path><path d=\\\"M12 19V5\\\"></path></svg>\",\"Square\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><rect width=\\\"18\\\" height=\\\"18\\\" x=\\\"3\\\" y=\\\"3\\\" rx=\\\"2\\\"></rect></svg>\",\"RotateCcw\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8\\\"></path><path d=\\\"M3 3v5h5\\\"></path></svg>\",\"Download\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M12 15V3\\\"></path><path d=\\\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\\\"></path><path d=\\\"m7 10 5 5 5-5\\\"></path></svg>\",\"Terminal\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M12 19h8\\\"></path><path d=\\\"m4 17 6-6-6-6\\\"></path></svg>\",\"ChevronDown\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"m6 9 6 6 6-6\\\"></path></svg>\",\"Maximize2\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M15 3h6v6\\\"></path><path d=\\\"m21 3-7 7\\\"></path><path d=\\\"m3 21 7-7\\\"></path><path d=\\\"M9 21H3v-6\\\"></path></svg>\",\"Minimize2\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"m14 10 7-7\\\"></path><path d=\\\"M20 10h-6V4\\\"></path><path d=\\\"m3 21 7-7\\\"></path><path d=\\\"M4 14h6v6\\\"></path></svg>\",\"LoaderCircle\":\"<svg class=\\\"icon \\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" width=\\\"18\\\" height=\\\"18\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"1.75\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\" aria-hidden=\\\"true\\\"><path d=\\\"M21 12a9 9 0 1 1-6.219-8.56\\\"></path></svg>\"};",
    "    const createAnswerPresenter = function createAnswerPresenter(element, renderMarkdown, onUpdate) {",
    "          let text = \"\";",
    "          let ended = false;",
    "          function render() {",
    "            if (!text)",
    "              return;",
    "            element.hidden = false;",
    "            element.innerHTML = renderMarkdown(text);",
    "            element.querySelectorAll(\".code-copy-btn\").forEach((button) => {",
    "              button.disabled = !ended;",
    "            });",
    "            onUpdate();",
    "          }",
    "          function finish() {",
    "            if (ended)",
    "              return;",
    "            ended = true;",
    "            element.classList.remove(\"is-revealing\");",
    "            render();",
    "          }",
    "          return {",
    "            append(delta) {",
    "              if (ended || !delta)",
    "                return;",
    "              text += delta;",
    "              element.classList.add(\"is-revealing\");",
    "              render();",
    "            },",
    "            finish() {",
    "              finish();",
    "              return Promise.resolve();",
    "            },",
    "            flush: finish,",
    "            cancel() {",
    "              ended = true;",
    "              element.classList.remove(\"is-revealing\");",
    "            }",
    "          };",
    "        };",
    "    const {host,protocol}=window.location;",
    "    let baseUrl='https://brew-cn.mintimate.cn';",
    "    if(host&&!/localhost|127\\.0\\.0\\.1/.test(host)&&protocol!=='file:') baseUrl=protocol+'//'+host;",
    "",
    "    // Update macOS commands",
    "    const macInstall=document.getElementById('install-command-macos');",
    "    const macUninstall=document.getElementById('uninstall-command-macos');",
    "    const macConfigure=document.getElementById('configure-command-macos');",
    "    if(macInstall) macInstall.textContent='/bin/zsh -c \"$(curl -fsSL '+baseUrl+'/install)\"';",
    "    if(macUninstall) macUninstall.textContent='/bin/zsh -c \"$(curl -fsSL '+baseUrl+'/install)\" -- --uninstall';",
    "    if(macConfigure) macConfigure.textContent='/bin/zsh -c \"$(curl -fsSL '+baseUrl+'/install)\" -- --configure';",
    "",
    "    // Update Linux commands",
    "    const linInstall=document.getElementById('install-command-linux');",
    "    const linUninstall=document.getElementById('uninstall-command-linux');",
    "    const linConfigure=document.getElementById('configure-command-linux');",
    "    if(linInstall) linInstall.textContent='/bin/bash -c \"$(curl -fsSL '+baseUrl+'/install)\"';",
    "    if(linUninstall) linUninstall.textContent='/bin/bash -c \"$(curl -fsSL '+baseUrl+'/install)\" -- --uninstall';",
    "    if(linConfigure) linConfigure.textContent='/bin/bash -c \"$(curl -fsSL '+baseUrl+'/install)\" -- --configure';",
    "",
    "    // Installer actions are a button group independent of the operating-system tabs.",
    "    window.switchOnboardingTask=function(task){",
    "        if(![\"install\",\"configure\",\"desktop\"].includes(task)) return;",
    "        document.querySelectorAll(\".onboarding-task\").forEach(button=>{",
    "            const selected=button.dataset.onboardingTask===task;",
    "            button.classList.toggle(\"active\",selected);",
    "            button.setAttribute(\"aria-pressed\",String(selected));",
    "        });",
    "        document.querySelectorAll(\".onboarding-content\").forEach(panel=>{panel.hidden=panel.dataset.onboardingPanel!==task;});",
    "    };",
    "    window.openDesktopHelp=function(){",
    "        window.openTroubleshootingGuide(\"desktop\");",
    "    };",
    "",
    "    // OS tab switching",
    "    window.switchOS=function(os){",
    "        document.querySelectorAll('.os-segment').forEach(t=>{const active=t.dataset.os===os;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});",
    "        document.querySelectorAll('.os-panel').forEach(p=>{p.hidden=p.id!=='os-'+os;});",
    "    };",
    "",
    "    // Terminal tab switching",
    "    window.switchTerminalTab=function(tabId){",
    "        const quickHelp=document.getElementById(\"quick-help\");if(quickHelp)quickHelp.hidden=tabId===\"ai-chat\";",
    "        const highlights=document.getElementById(\"feature-highlights\");if(highlights)highlights.hidden=tabId===\"ai-chat\";",
    "        document.querySelectorAll('.terminal-tab').forEach(t=>{const active=t.dataset.tab===tabId;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});",
    "        document.querySelectorAll('.terminal-panel').forEach(p=>{",
    "            if(p.id==='panel-'+tabId){",
    "                p.hidden=false;",
    "                p.classList.add('active');",
    "            } else {",
    "                p.hidden=true;",
    "                p.classList.remove('active');",
    "            }",
    "        });",
    "    };",
    "",
    "    // Auto-detect OS from User-Agent",
    "    (function(){",
    "        const ua=navigator.userAgent||navigator.platform||'';",
    "        if(/Linux/i.test(ua)&&!/Android/i.test(ua)) switchOS('linux');",
    "    })();",
    "",
    "    let copyToastTimer;",
    "    async function copyText(text, btn) {",
    "        if (btn.disabled) return;",
    "        const original=btn.innerHTML, label=btn.getAttribute(\"aria-label\"), tooltip=btn.dataset.tooltip;",
    "        btn.disabled=true;",
    "        let copied=false;",
    "        try {",
    "            if (navigator.clipboard && navigator.clipboard.writeText) { await navigator.clipboard.writeText(text); copied=true; }",
    "            else {",
    "                const focused=document.activeElement, field=document.createElement(\"textarea\");",
    "                field.value=text; field.style.cssText=\"position:fixed;opacity:0\"; document.body.appendChild(field); field.select();",
    "                try { copied=Boolean(document.execCommand(\"copy\")); } finally { field.remove(); if(focused)focused.focus(); }",
    "            }",
    "        } catch(e) { copied=false; }",
    "        const message=copied?\"已复制到剪贴板\":\"复制失败，请选择命令后手动复制\";",
    "        btn.innerHTML=UI_ICONS[copied?\"Check\":\"X\"]; btn.setAttribute(\"aria-label\",message); btn.dataset.tooltip=message;",
    "        btn.classList.add(copied?\"copied\":\"copy-failed\");",
    "        const feedback=document.getElementById(\"copy-feedback\");",
    "        clearTimeout(copyToastTimer); if(feedback)feedback.textContent=message;",
    "        copyToastTimer=setTimeout(()=>{if(feedback)feedback.textContent=\"\";},3000);",
    "        setTimeout(()=>{btn.innerHTML=original;btn.disabled=false;btn.classList.remove(\"copied\",\"copy-failed\");if(label)btn.setAttribute(\"aria-label\",label);else btn.removeAttribute(\"aria-label\");if(tooltip)btn.dataset.tooltip=tooltip;else delete btn.dataset.tooltip;},1800);",
    "    }",
    "    function copyCommand(id,btn){",
    "        return copyText(document.getElementById(id).textContent,btn);",
    "    }",
    "",
    "    const THEME_KEY='brew-cn-theme';",
    "    const mediaDark=window.matchMedia('(prefers-color-scheme: dark)');",
    "    const THEME_MODES=['light','system','dark'];",
    "    function getSavedThemeMode(){",
    "        let saved; try { saved=localStorage.getItem(THEME_KEY); } catch(e) {}",
    "        return THEME_MODES.includes(saved)?saved:'system';",
    "    }",
    "    function resolveTheme(mode){",
    "        return mode==='system'?(mediaDark.matches?'dark':'light'):mode;",
    "    }",
    "    function applyThemeMode(mode,{persist=false}={}){",
    "        const resolved=resolveTheme(mode);",
    "        document.documentElement.setAttribute('data-theme',resolved);",
    "        document.querySelectorAll(\"[data-theme-mode]\").forEach(btn=>btn.setAttribute(\"aria-pressed\",String(btn.dataset.themeMode===mode)));",
    "        if(persist) { try { localStorage.setItem(THEME_KEY,mode); } catch(e) {} }",
    "    }",
    "    function setupThemeToggle(){",
    "        applyThemeMode(getSavedThemeMode());",
    "        document.querySelectorAll(\"[data-theme-mode]\").forEach(btn=>btn.addEventListener(\"click\",()=>applyThemeMode(btn.dataset.themeMode,{persist:true})));",
    "        const handleChange=()=>{",
    "            if(getSavedThemeMode()==='system') applyThemeMode('system');",
    "        };",
    "        if(mediaDark.addEventListener) mediaDark.addEventListener('change',handleChange);",
    "        else if(mediaDark.addListener) mediaDark.addListener(handleChange);",
    "    }",
    "",
    "    const fu=v=>v&&!/unknown/i.test(v)?v:'';",
    "    function timeAgo(t){const d=new Date(t),ms=Date.now()-d,m=ms/6e4|0,h=ms/36e5|0,dy=ms/864e5|0;return m<1?'刚刚':m<60?m+'分钟前':h<24?h+'小时前':dy<30?dy+'天前':d.toLocaleDateString('zh-CN')}",
    "    const INITIAL_SHOW=3;",
    "    let allInstalls=[];",
    "    function renderRecentInstalls(installs){",
    "        const c=document.getElementById('recent-installs');",
    "        if(!installs||!installs.length){c.innerHTML='<div style=\"text-align:center;color:var(--text-muted);font-size:.9rem;padding:16px 0\">暂无脚本获取记录</div>';return}",
    "        allInstalls=installs;",
    "        renderInstallList(INITIAL_SHOW);",
    "    }",
    "    function renderInstallItem(i){",
    "        const loc=[fu(i.city),fu(i.region),fu(i.country)].filter(Boolean).join(', ')||'未知地区';",
    "        const item=document.createElement('div');item.className='recent-item';",
    "        const location=document.createElement('span');location.className='ri-location';location.title=loc;location.textContent=loc;",
    "        const time=document.createElement('span');time.className='ri-time';time.textContent=timeAgo(i.time);item.append(location,time);return item.outerHTML;",
    "    }",
    "    function renderInstallList(count){",
    "        const c=document.getElementById('recent-installs');",
    "        const btnContainer=document.getElementById('recent-toggle-container');",
    "        const showing=allInstalls.slice(0,count);",
    "        c.innerHTML=showing.map(renderInstallItem).join('');",
    "        ",
    "        if(!btnContainer) return;",
    "        if(count<allInstalls.length){",
    "            btnContainer.innerHTML='<button class=\"recent-toggle-btn\" onclick=\"expandInstalls()\">展开更多（共 '+allInstalls.length+' 条）</button>';",
    "        }else if(allInstalls.length>INITIAL_SHOW){",
    "            btnContainer.innerHTML='<button class=\"recent-toggle-btn\" onclick=\"collapseInstalls()\">收起</button>';",
    "        }else{",
    "            btnContainer.innerHTML='';",
    "        }",
    "    }",
    "    window.expandInstalls=function(){renderInstallList(allInstalls.length)};",
    "    window.collapseInstalls=function(){renderInstallList(INITIAL_SHOW)};",
    "",
    "    async function fetchStats(){",
    "        try{",
    "            const r=await(await fetch('/api/stats')).json();",
    "            if(r.code!==0)throw new Error(\"Stats unavailable\");",
    "            document.getElementById('total-calls').textContent=r.data.totalCalls.toLocaleString();",
    "            const t=r.data.lastCallTime;",
    "            const el=document.getElementById('last-call');el.textContent=t?timeAgo(t):'暂无记录';el.title=t?new Date(t).toLocaleString('zh-CN'):'';",
    "            renderRecentInstalls(r.data.recentInstalls||[]);",
    "        }catch(e){const list=document.getElementById(\"recent-installs\");if(!allInstalls.length)list.textContent=\"暂时无法获取脚本获取记录\";}",
    "    }",
    "",
    "    (function(){",
    "        setupThemeToggle();",
    "        fetchStats();setInterval(fetchStats,3e4);",
    "        const roomyViewport=window.matchMedia(\"(min-width: 1000px) and (min-height: 760px)\");",
    "        const helpPanels=Array.from(document.querySelectorAll(\"[data-responsive-help]\"));",
    "        function updateHelpLayout(){helpPanels.forEach(panel=>{if(!panel.dataset.userToggled)panel.open=roomyViewport.matches;});}",
    "        helpPanels.forEach(panel=>panel.querySelector(\"summary\").addEventListener(\"click\",()=>{panel.dataset.userToggled=\"true\";}));",
    "        if(roomyViewport.addEventListener)roomyViewport.addEventListener(\"change\",updateHelpLayout);else if(roomyViewport.addListener)roomyViewport.addListener(updateHelpLayout);",
    "        updateHelpLayout();",
    "        document.querySelectorAll(\"[role=tablist]\").forEach(list=>list.addEventListener(\"keydown\",e=>{",
    "            if(![\"ArrowLeft\",\"ArrowRight\",\"Home\",\"End\"].includes(e.key))return;",
    "            const tabs=Array.from(list.querySelectorAll(\"[role=tab]\")),index=tabs.indexOf(document.activeElement);",
    "            if(index<0)return;e.preventDefault();const next=e.key===\"Home\"?0:e.key===\"End\"?tabs.length-1:(index+(e.key===\"ArrowRight\"?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus();",
    "        }));",
    "        const workspace=document.getElementById(\"ai-chat-window\"),expand=document.getElementById(\"workspace-expand\");",
    "        let previousInert=[];",
    "        function resizeWorkspace(){if(workspace.classList.contains(\"expanded\")&&window.visualViewport)workspace.style.maxHeight=window.visualViewport.height+\"px\";}",
    "        function setExpanded(value){",
    "            workspace.classList.toggle(\"expanded\",value);document.body.classList.toggle(\"workspace-expanded\",value);expand.setAttribute(\"aria-pressed\",String(value));",
    "            expand.innerHTML=UI_ICONS[value?\"Minimize2\":\"Maximize2\"];const label=value?\"收起工作区\":\"展开工作区\";expand.setAttribute(\"aria-label\",label);expand.dataset.tooltip=label;",
    "            if(value){previousInert=Array.from(document.querySelectorAll(\".site-header,.hero,main > :not(#ai-chat-window),.footer\")).map(el=>[el,el.inert]);previousInert.forEach(([el])=>el.inert=true);resizeWorkspace();}",
    "            else{previousInert.forEach(([el,inert])=>el.inert=inert);workspace.style.maxHeight=\"\";expand.focus();}",
    "        }",
    "        expand.addEventListener(\"click\",()=>setExpanded(!workspace.classList.contains(\"expanded\")));",
    "        if(window.visualViewport)window.visualViewport.addEventListener(\"resize\",resizeWorkspace);",
    "        document.addEventListener(\"keydown\",e=>{",
    "            if(!workspace.classList.contains(\"expanded\"))return;",
    "            if(e.key===\"Escape\"){setExpanded(false);return;}",
    "            if(e.key!==\"Tab\")return;",
    "            const items=Array.from(workspace.querySelectorAll(\"button:not(:disabled),a[href],textarea,summary,[tabindex=\\\"0\\\"]\")).filter(el=>el.getClientRects().length&&el.tabIndex>=0);",
    "            const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}",
    "        });",
    "",
    "",
    "        // 隐藏彩蛋：连续输入 brew 显示腾讯云镜像源",
    "        let eggBuf='',eggTimer=null;",
    "        document.addEventListener('keydown',function(e){",
    "            if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;",
    "            clearTimeout(eggTimer);",
    "            eggBuf+=e.key.toLowerCase();",
    "            eggTimer=setTimeout(()=>{eggBuf=''},2000);",
    "            if(eggBuf.includes('brew')){",
    "                eggBuf='';",
    "                const row=document.getElementById('mirror-egg');",
    "                if(row&&!row.classList.contains('egg-show')){",
    "                    row.classList.add('egg-show');",
    "                    const help=document.getElementById(\"installation-help\");if(help)help.open=true;",
    "                    row.scrollIntoView({behavior:'smooth',block:'center'});",
    "                }",
    "            }",
    "        });",
    "    })();",
    "",
    "    // === AI Chat Agent Client Logic (Tool Calling Thinking Chain) ===",
    "    (function() {",
    "        const chatWindow = document.getElementById(\"ai-chat-window\");",
    "        const chatInput = document.getElementById(\"chat-input\");",
    "        const sendBtn = document.getElementById(\"chat-send-btn\");",
    "        const messagesContainer = document.getElementById(\"chat-messages\");",
    "        const agentToolPanel = document.getElementById(\"agent-tool-panel\");",
    "        const attachmentsEl = document.getElementById(\"chat-attachments\");",
    "        const MAX_PASTED_IMAGES = 3;",
    "        const MAX_PASTED_IMAGE_BYTES = 2 * 1024 * 1024;",
    "        let pendingImages = [];",
    "        let isGenerating = false;",
    "        let activeRequest = null;",
    "        let followLatest = true;",
    "        let packageQueryMode = false;",
    "        const jumpLatest = document.getElementById(\"chat-jump-latest\");",
    "        const chatFeedback = document.getElementById(\"chat-feedback\");",
    "",
    "        if (!chatWindow) return;",
    "",
    "        function createConversationId() {",
    "            if (window.crypto && typeof window.crypto.randomUUID === \"function\") return \"conv_\" + window.crypto.randomUUID().replace(/-/g, \"\").slice(0, 31);",
    "            return (\"conv_\" + Date.now().toString(36) + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)).slice(0, 36);",
    "        }",
    "        // One page lifecycle = one chat session; do not persist this in localStorage.",
    "        let convId = createConversationId();",
    "",
    "        // Input button state",
    "        chatInput.addEventListener(\"input\", () => {",
    "            resizeChatInput();",
    "            updateSendState();",
    "        });",
    "",
    "        function updateSendState() {",
    "            sendBtn.disabled = !isGenerating && !chatInput.value.trim() && pendingImages.length === 0;",
    "            sendBtn.innerHTML=UI_ICONS[isGenerating?\"Square\":\"ArrowUp\"];",
    "            sendBtn.classList.toggle(\"generating\",isGenerating);",
    "            sendBtn.setAttribute(\"aria-label\",isGenerating?\"停止生成\":\"发送消息\");",
    "            sendBtn.dataset.tooltip=isGenerating?\"停止生成\":\"发送消息\";",
    "            document.querySelectorAll(\".answer-followup,#chat-new-conversation\").forEach(button=>{button.disabled=isGenerating;});",
    "        }",
    "        function resizeChatInput(){chatInput.style.height=\"auto\";const style=getComputedStyle(chatInput);const min=parseFloat(style.minHeight)||96,max=parseFloat(style.maxHeight)||200;chatInput.style.height=Math.min(max,Math.max(min,chatInput.scrollHeight))+\"px\";}",
    "        window.addEventListener(\"resize\",resizeChatInput);",
    "        function setPackageQueryMode(active){",
    "            packageQueryMode=active;document.getElementById(\"package-query-mode\").hidden=!active;",
    "            chatInput.placeholder=active?\"软件包或应用名，如 git、vscode\":\"输入问题，或粘贴多行终端日志…\";",
    "            updateSendState();",
    "        }",
    "        document.getElementById(\"package-query-cancel\").addEventListener(\"click\",()=>{setPackageQueryMode(false);chatInput.focus();});",
    "        function scrollToLatest(force=false){",
    "            if(force)followLatest=true;",
    "            if(followLatest)messagesContainer.scrollTop=messagesContainer.scrollHeight;",
    "            jumpLatest.hidden=followLatest;",
    "        }",
    "        messagesContainer.addEventListener(\"scroll\",()=>{",
    "            followLatest=messagesContainer.scrollHeight-messagesContainer.scrollTop-messagesContainer.clientHeight<64;",
    "            jumpLatest.hidden=followLatest;",
    "        });",
    "        jumpLatest.addEventListener(\"click\",()=>scrollToLatest(true));",
    "        function openChat(){switchTerminalTab(\"ai-chat\");chatWindow.scrollIntoView({block:\"start\"});chatInput.focus({preventScroll:true});}",
    ...getTroubleshootingClientLines(),
    ...getConversationClientLines(),
    "        document.querySelectorAll(\"[data-open-chat]\").forEach(btn=>btn.addEventListener(\"click\",openChat));",
    "        document.querySelectorAll(\"[data-run-mirror]\").forEach(btn=>btn.addEventListener(\"click\",()=>{openChat();sendMessage(\"运行在线镜像检测\");}));",
    "        document.querySelectorAll(\"[data-quick-action]\").forEach(btn=>btn.addEventListener(\"click\",()=>{",
    "            if(isGenerating)return;",
    "            if(btn.dataset.quickAction===\"search\"){setPackageQueryMode(true);chatInput.focus();return;}",
    "            if([\"doctor\",\"desktop\"].includes(btn.dataset.quickAction)){window.openTroubleshootingGuide(btn.dataset.quickAction);return;}",
    "            const prompts={mirror:\"运行在线镜像检测\",missing:\"找不到 brew 命令，应该如何排查？\",restore:\"如何恢复官方源？\"};",
    "            sendMessage(prompts[btn.dataset.quickAction]);",
    "        }));",
    "        function addRetry(skeleton,text,images){",
    "            const retry=document.createElement(\"button\");retry.className=\"retry-btn\";retry.innerHTML=UI_ICONS.RotateCcw+\"重试\";",
    "            retry.addEventListener(\"click\",()=>{if(!isGenerating)sendMessage(text,images);});skeleton.bubble.appendChild(retry);",
    "        }",
    "",
    "        function formatBytes(size) {",
    "            if (size < 1024) return size + \" B\";",
    "            if (size < 1024 * 1024) return (size / 1024).toFixed(1) + \" KB\";",
    "            return (size / 1024 / 1024).toFixed(1) + \" MB\";",
    "        }",
    "",
    "        function renderAttachments() {",
    "            if (!attachmentsEl) return;",
    "            if (!pendingImages.length) { attachmentsEl.innerHTML = \"\"; return; }",
    "            attachmentsEl.innerHTML = pendingImages.map(function(image, index) {",
    "                return '<span class=\"attachment-chip image-chip\" title=\"粘贴的截图\"><span>粘贴的截图</span><small>' + formatBytes(image.size) + '</small><button type=\"button\" aria-label=\"移除截图\" onclick=\"removeChatAttachment(' + index + ')\">&times;</button></span>';",
    "            }).join(\"\");",
    "        }",
    "",
    "        window.removeChatAttachment = function(index) {",
    "            pendingImages.splice(index, 1);",
    "            renderAttachments();",
    "            updateSendState();",
    "        };",
    "",
    "        function readImageAsBase64(file) {",
    "            return new Promise(function(resolve, reject) {",
    "                const reader = new FileReader();",
    "                reader.onload = function() {",
    "                    const value = String(reader.result || \"\");",
    "                    resolve({ name: file.name, type: file.type || \"\", size: file.size, base64: value.includes(\",\") ? value.split(\",\").pop() : value });",
    "                };",
    "                reader.onerror = function() { reject(reader.error || new Error(\"读取文件失败\")); };",
    "                reader.readAsDataURL(file);",
    "            });",
    "        }",
    "",
    "        chatInput.addEventListener(\"paste\", function(event) {",
    "            const items = Array.from(event.clipboardData && event.clipboardData.items ? event.clipboardData.items : []);",
    "            const images = items.map(function(item) { return item.kind === \"file\" && item.type.indexOf(\"image/\") === 0 ? item.getAsFile() : null; }).filter(Boolean);",
    "            if (!images.length) return;",
    "            event.preventDefault();",
    "            images.forEach(function(file) {",
    "                if (pendingImages.length >= MAX_PASTED_IMAGES) { chatFeedback.textContent=\"最多可添加 3 张截图。\"; return; }",
    "                if (file.size > MAX_PASTED_IMAGE_BYTES) { chatFeedback.textContent=\"截图过大，单张不能超过 2 MB。\"; return; }",
    "                pendingImages.push(file);",
    "            });",
    "            renderAttachments();",
    "            updateSendState();",
    "        });",
    "",
    "        // Enter inserts a newline; Ctrl/Cmd + Enter explicitly sends.",
    "        chatInput.addEventListener(\"keydown\", (e) => {",
    "            if (e.key === \"Enter\" && (e.ctrlKey || e.metaKey) && !e.shiftKey && !e.altKey && !e.isComposing && e.keyCode !== 229) {",
    "                e.preventDefault();",
    "                sendMessage();",
    "            }",
    "        });",
    "",
    "        sendBtn.addEventListener(\"click\", () => {",
    "            if(isGenerating&&activeRequest){activeRequest.stopped=true;activeRequest.controller.abort();if(activeRequest.presenter){activeRequest.presenter.flush();activeRequest.presenter.cancel();}if(activeRequest.reader)activeRequest.reader.cancel().catch(()=>{});return;}",
    "            sendMessage();",
    "        });",
    "",
    "        window.sendQuickAction = function(text, images) {",
    "            sendMessage(text, images);",
    "        };",
    "",
    "        window.quickDiagnose = function(text) {",
    "            window.sendQuickAction(text);",
    "        };",
    "",
    "        // Event delegation for copy buttons in AI messages",
    "        messagesContainer.addEventListener('click', function(e) {",
    "            const btn = e.target.closest('.code-copy-btn');",
    "            if (btn) {",
    "                const pre = btn.closest('pre');",
    "                const codeEl = pre ? pre.querySelector('code') : null;",
    "                if (codeEl) {",
    "                    const text = codeEl.textContent;",
    "                    copyText(text,btn);",
    "                }",
    "            }",
    "        });",
    "",
    "        // Configure marked options if available",
    "        function setupMarkdownRenderer() {",
    "            if (typeof marked === \"undefined\") return;",
    "            const renderer = new marked.Renderer();",
    "            renderer.code = function(arg1, arg2, arg3) {",
    "                let code = '';",
    "                let lang = 'text';",
    "                if (typeof arg1 === 'object' && arg1 !== null) {",
    "                    code = arg1.text || arg1.raw || '';",
    "                    lang = arg1.lang || 'text';",
    "                } else {",
    "                    code = arg1 || '';",
    "                    lang = arg2 || 'text';",
    "                }",
    "                const escapedCode = escapeHtml(code);",
    "                const escapedLang = escapeHtml(lang || 'text');",
    "                return '<pre class=\"command-box code-snippet\" data-lang=\"' + escapedLang + '\">' +",
    "                       '<button class=\"code-copy-btn\" aria-label=\"复制代码\">' +",
    "                       '<svg viewBox=\"0 0 24 24\" width=\"12\" height=\"12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" style=\"margin-right:2px\"><rect x=\"9\" y=\"9\" width=\"13\" height=\"13\" rx=\"2\" ry=\"2\"/><path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"/></svg>' +",
    "                       '<span>复制</span>' +",
    "                       '</button>' +",
    "                       '<code>' + escapedCode + '</code></pre>';",
    "            };",
    "            marked.use({ renderer });",
    "        }",
    "        document.addEventListener(\"DOMContentLoaded\",setupMarkdownRenderer);",
    "",
    "        // Markdown parser with fallback support",
    "        function parseMarkdown(text) {",
    "            if (typeof marked !== 'undefined' && typeof marked.parse === 'function') {",
    "                try {",
    "                    return marked.parse(String(text || \"\"));",
    "                } catch (e) {",
    "                    console.error(\"marked parse error:\", e);",
    "                }",
    "            }",
    "            const codeBlocks = [];",
    "            const source = String(text || \"\").replace(/^\\s+/, \"\").replace(/\\n{3,}/g, \"\\n\\n\");",
    "            let html = source.replace(/```(\\w*)\\n?([\\s\\S]*?)```/g, function(match, lang, code) {",
    "                const placeholder = \"%%CODE_BLOCK_\" + codeBlocks.length + \"%%\";",
    "                const cleanCode = code.replace(/^\\n+|\\n+$/g, \"\");",
    "                const label = lang || \"text\";",
    "                codeBlocks.push('<pre class=\"command-box code-snippet\" data-lang=\"' + escapeHtml(label) + '\"><button class=\"code-copy-btn\" aria-label=\"复制代码\"><svg viewBox=\"0 0 24 24\" width=\"12\" height=\"12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" style=\"margin-right:2px\"><rect x=\"9\" y=\"9\" width=\"13\" height=\"13\" rx=\"2\" ry=\"2\"/><path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"/></svg><span>复制</span></button><code>' + escapeHtml(cleanCode) + '</code></pre>');",
    "                return placeholder;",
    "            });",
    "            html = html.replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\");",
    "            html = html.replace(/`([^`]+)`/g, \"<code style=\\\"background:rgba(255,140,66,0.1);padding:2px 6px;border-radius:4px;font-family:monospace;color:var(--accent);\\\">$1</code>\");",
    "            html = html.replace(/\\*\\*([^*]+)\\*\\*/g, \"<strong>$1</strong>\");",
    "            ",
    "            // Headings",
    "            html = html.replace(/^(#{1,6})\\s+(.+)$/gm, function(match, hashes, content) {",
    "                const level = hashes.length;",
    "                return \"<h\" + level + \">\" + content.trim() + \"</h\" + level + \">\";",
    "            });",
    "            ",
    "            // Lists",
    "            html = html.replace(/^\\s*[-*+]\\s+(.+)$/gm, \"<ul><li>$1</li></ul>\");",
    "            html = html.replace(/<\\/ul>\\s*<ul>/g, \"\");",
    "            html = html.replace(/^\\s*(\\d+)\\.\\s+(.+)$/gm, \"<ol><li value=\\\"$1\\\">$2</li></ol>\");",
    "            html = html.replace(/<\\/ol>\\s*<ol>/g, \"\");",
    "            ",
    "            html = html.replace(/\\n/g, \"<br>\");",
    "            ",
    "            // Clean up extra line breaks around lists and headings",
    "            html = html.replace(/<(h[1-6]|ul|ol|li|pre|code)([^>]*)><br>/g, \"<$1$2>\");",
    "            html = html.replace(/<br><\\/(h[1-6]|ul|ol|li|pre|code)>/g, \"</$1>\");",
    "            html = html.replace(/<\\/(h[1-6]|ul|ol|pre|code)><br>/g, \"</$1>\");",
    "            html = html.replace(/^(<br>)+/g, \"\");",
    "            html = html.replace(/(<br>\\s*){3,}/g, \"<br><br>\");",
    "            codeBlocks.forEach(function(block, index) {",
    "                html = html.replace(\"%%CODE_BLOCK_\" + index + \"%%\", block);",
    "            });",
    "            return html;",
    "        }",
    "",
    "        // ═══ Agent 消息结构常量 ═══",
    "        const AGENT_MSG = {",
    "            ROW_CLS: \"agent-message-row\",",
    "            AVATAR_CLS: \"agent-avatar\",",
    "            BUBBLE_CLS: \"agent-bubble\",",
    "            LOGS_FLOW_CLS: \"agent-logs-flow\",",
    "            TEXT_CONTENT_CLS: \"agent-text-content\",",
    "            USAGE_CLS: \"agent-usage\",",
    "        };",
    "",
    "        let activeAssistantMessage = null;",
    "        let activeTextContent = null;",
    "        let activeUsageElement = null;",
    "        let currentToolName = \"\";",
    "        let activeToolCards = new Map();",
    "        let toolStepCounter = 0;",
    "        let diagnosticState = { analysis: null, fix: \"\" };",
    "",
    "        /** 创建 Agent 回复骨架（avatar + bubble + 推理链容器） */",
    "        function createAgentSkeleton() {",
    "            const row = document.createElement(\"div\");",
    "            row.className = AGENT_MSG.ROW_CLS;row.setAttribute(\"aria-busy\",\"true\");",
    "            row.innerHTML =",
    "                '<div class=\"' + AGENT_MSG.AVATAR_CLS + '\">' + UI_ICONS.Assistant + '</div>' +",
    "                '<div class=\"' + AGENT_MSG.BUBBLE_CLS + '\"></div>';",
    "            messagesContainer.appendChild(row);",
    "            const bubble = row.querySelector(\".\" + AGENT_MSG.BUBBLE_CLS);",
    "",
    "            // 推理链容器（始终创建，可折叠）",
    "            const tw = document.createElement(\"details\");",
    "            tw.className = \"thinking-wrapper is-working\";tw.open=true;",
    "            tw.innerHTML =",
    "                '<summary class=\"thinking-header\"><span class=\"progress-icon\">' + UI_ICONS.LoaderCircle + '</span>' +",
    "                '<span class=\"progress-title\">正在阅读你的问题</span><span class=\"progress-elapsed\" aria-hidden=\"true\">0.0 秒</span>' + UI_ICONS.ChevronDown + '</summary>' +",
    "                '<section class=\"model-reasoning\" aria-label=\"模型思考\" hidden><h3>模型思考</h3><div class=\"reasoning-content\"></div></section>' +",
    "                '<div class=\"thinking-content\" style=\"display:none\"></div>' +",
    "                '<div class=\"thinking-body\"></div>';",
    "",
    "            const thinkingBody = tw.querySelector(\".thinking-body\");",
    "            const thinkingContentEl = tw.querySelector(\".thinking-content\");",
    "            tw.querySelector(\"summary\").addEventListener(\"click\",()=>{tw.dataset.userToggled=\"true\";});",
    "",
    "",
    "            // 最终回答文本区",
    "            const textContent = document.createElement(\"div\");",
    "            textContent.className = AGENT_MSG.TEXT_CONTENT_CLS;",
    "            textContent.hidden=true;",
    "            textContent.innerHTML = '<div class=\"typing-indicator\"><span></span><span></span><span></span></div>';",
    "            bubble.appendChild(tw);",
    "            bubble.appendChild(textContent);",
    "",
    "            const usageEl = document.createElement(\"div\");",
    "            usageEl.className = AGENT_MSG.USAGE_CLS;",
    "            usageEl.style.display = \"none\";",
    "            tw.appendChild(usageEl);",
    "            ",
    "            const skeleton={ row, bubble, thinkingWrapper: tw, thinkingBody, thinkingContent: thinkingContentEl, textContent, usageEl, startedAt:Date.now(), progressTitle:tw.querySelector(\".progress-title\"), progressElapsed:tw.querySelector(\".progress-elapsed\"), reasoningSection:tw.querySelector(\".model-reasoning\"), reasoningContent:tw.querySelector(\".reasoning-content\"), reasoningText:\"\", reasoningResponseId:null };",
    "            skeleton.progressTimer=setInterval(()=>updateProgressElapsed(skeleton),500);",
    "            return skeleton;",
    "        }",
    "        function updateProgressElapsed(skeleton){skeleton.progressElapsed.textContent=(((skeleton.finishedAt||Date.now())-skeleton.startedAt)/1000).toFixed(1)+\" 秒\";}",
    "        function finishProgress(skeleton,{stopped=false,failed=false,keepOpen=false}={}){",
    "            clearInterval(skeleton.progressTimer);updateProgressElapsed(skeleton);",
    "            const details=skeleton.thinkingWrapper;",
    "            details.classList.remove(\"is-working\");details.classList.add(stopped?\"is-stopped\":failed?\"is-failed\":\"is-complete\");",
    "            details.querySelector(\".progress-icon\").innerHTML=UI_ICONS[stopped?\"Square\":failed?\"X\":\"Check\"];",
    "            skeleton.progressTitle.textContent=(stopped?\"已停止\":failed?\"处理未完成\":\"处理完成\")+(toolStepCounter?\" · \"+toolStepCounter+\" 个步骤\":\"\");",
    "            if(agentToolPanel)agentToolPanel.textContent=skeleton.progressTitle.textContent+\" · \"+skeleton.progressElapsed.textContent;",
    "            details.querySelectorAll(\".tool-call-header.running\").forEach(header=>{header.className=\"tool-call-header interrupted\";header.innerHTML=UI_ICONS[stopped?\"Square\":\"X\"]+\"<span>\"+(stopped?\"已停止等待此步骤\":\"此步骤未完成\")+\"</span>\";});",
    "            if(!details.dataset.userToggled)details.open=keepOpen||failed||Boolean(skeleton.reasoningText);",
    "            skeleton.row.setAttribute(\"aria-busy\",\"false\");",
    "        }",
    "",
    "        function renderGlobalToolPanel() {",
    "            if (!agentToolPanel) return;",
    "            agentToolPanel.textContent=\"Homebrew 助手\";",
    "        }",
    "",
    "        function resetGlobalToolPanel() {",
    "            if (!agentToolPanel) return;",
    "            agentToolPanel.classList.remove(\"running\");",
    "        }",
    "",
    "        function markToolActive(toolName, state) {",
    "            if (!agentToolPanel || !toolName) return;",
    "            agentToolPanel.textContent=(state===\"success\"?\"已完成：\":\"正在处理：\")+toolLabel(toolName);",
    "            agentToolPanel.classList.toggle(\"running\",state!==\"success\");",
    "        }",
    "        renderGlobalToolPanel();",
    "",
    "        // Server progress summaries and provider-returned reasoning use separate regions.",
    "        var thinkingText = \"\";",
    "",
    "        function handleThinkingEvent(skeleton, content) {",
    "            if (!skeleton || !skeleton.thinkingWrapper) return;",
    "            const summary=String(content||\"\").trim();if(!summary||summary===thinkingText)return;thinkingText=summary;",
    "            var tc = skeleton.thinkingContent;",
    "            const entry=document.createElement(\"p\");entry.className=\"progress-summary\";entry.textContent=summary;tc.appendChild(entry);",
    "            tc.style.display = \"\";",
    "            tc.scrollTop = tc.scrollHeight;",
    "            scrollToLatest();",
    "        }",
    "",
    "        function resetThinking() { thinkingText = \"\"; toolStepCounter = 0; }",
    "        function handleReasoningEvent(skeleton,event){",
    "            if(typeof event.content!==\"string\"||!event.content.length)return;",
    "            const content=skeleton.reasoningContent,position=content.scrollTop;",
    "            const follow=content.scrollHeight-position-content.clientHeight<32;",
    "            if(event.response_id&&skeleton.reasoningResponseId&&event.response_id!==skeleton.reasoningResponseId)skeleton.reasoningText+=\"\\n\\n\";",
    "            if(event.response_id)skeleton.reasoningResponseId=event.response_id;",
    "            skeleton.reasoningText+=event.content;content.textContent=skeleton.reasoningText;",
    "            skeleton.reasoningSection.hidden=false;skeleton.thinkingContent.hidden=true;",
    "            if(!skeleton.thinkingWrapper.dataset.userToggled)skeleton.thinkingWrapper.open=true;",
    "            setStatus(\"正在思考…\",skeleton);",
    "            content.scrollTop=follow?content.scrollHeight:position;scrollToLatest();",
    "        }",
    "",
    "        function formatEventClock() {",
    "            var now = new Date();",
    "            var hh = String(now.getHours()).padStart(2, \"0\");",
    "            var mm = String(now.getMinutes()).padStart(2, \"0\");",
    "            var ss = String(now.getSeconds()).padStart(2, \"0\");",
    "            return hh + \":\" + mm + \":\" + ss;",
    "        }",
    "",
    "        function formatToolArguments(rawArgs) {",
    "            if (rawArgs === null || rawArgs === undefined || rawArgs === \"\") return \"{}\";",
    "            if (typeof rawArgs === \"object\") return JSON.stringify(rawArgs, null, 2);",
    "            var text = String(rawArgs);",
    "            try {",
    "                return JSON.stringify(JSON.parse(text), null, 2);",
    "            } catch (e) {",
    "                return text;",
    "            }",
    "        }",
    "",
    "        // ── Tool Call 卡片（✅ 工具执行成功 + 结果框） ─────────────────────",
    "        function handleToolCallEvent(skeleton, toolName, toolArgs) {",
    "            var body = skeleton.thinkingBody;",
    "            if (!body) return null;",
    "            markToolActive(toolName, \"running\");",
    "            toolStepCounter += 1;",
    "            var blockId = \"tool-\" + toolName.replace(/:/g, \"-\") + \"-\" + Date.now();",
    "            var block = document.createElement(\"div\");",
    "            block.className = \"tool-call-log\";",
    "            block.id = blockId;",
    "            block.dataset.toolName = toolName;",
    "            block.dataset.toolStep = String(toolStepCounter);",
    "            var formattedArgs = formatToolArguments(toolArgs);",
    "            var showArgs = toolName !== \"intent_classify\" && formattedArgs !== \"{}\";",
    "            block.innerHTML =",
    "                '<div class=\"tool-call-header running\">' +",
    "                '<svg class=\"spin-svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 2v4\"/></svg>' +",
    "                '<span>步骤 ' + toolStepCounter + ' · 正在调用工具: ' + escapeHtml(toolLabel(toolName)) + '...</span><span class=\"tool-time\">' + formatEventClock() + '</span></div>';",
    "            if (showArgs) {",
    "                block.innerHTML += '<details class=\"tool-call-args\"><summary>工具入参</summary><pre class=\"tool-call-output tool-call-args-code\">' + escapeHtml(formattedArgs) + '</pre></details>';",
    "            }",
    "            body.appendChild(block);",
    "            activeToolCards.set(blockId, { el: block, name: toolName, done: false });",
    "            scrollToLatest();",
    "            return blockId;",
    "        }",
    "",
    "        function handleToolResultEvent(skeleton, toolName, resultText, partial) {",
    "            var body = skeleton ? skeleton.thinkingBody : null;",
    "            if (!body) return;",
    "            markToolActive(toolName, partial ? \"running\" : \"success\");",
    "            var items = body.querySelectorAll(\".tool-call-log\");",
    "            var matchedBlock = null;",
    "            for (var i = items.length - 1; i >= 0; i--) {",
    "                var header = items[i].querySelector(\".tool-call-header\");",
    "                if (header && header.classList.contains(\"running\") && items[i].dataset.toolName === toolName) {",
    "                    matchedBlock = items[i]; break;",
    "                }",
    "            }",
    "            if (matchedBlock) {",
    "                var header = matchedBlock.querySelector(\".tool-call-header\");",
    "                var stepText = matchedBlock.dataset.toolStep ? (\"步骤 \" + matchedBlock.dataset.toolStep + \" · \") : \"\";",
    "                if (partial) {",
    "                    header.className = \"tool-call-header running\";",
    "                    header.innerHTML =",
    "                        '<svg class=\"spin-svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 2v4\"/></svg>' +",
    "                        '<span>' + stepText + '工具执行中: ' + escapeHtml(toolLabel(toolName)) + '</span><span class=\"tool-time\">' + formatEventClock() + '</span>';",
    "                } else {",
    "                    header.className = \"tool-call-header success\";",
    "                    header.innerHTML =",
    "                        '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><polyline points=\"20 6 9 17 4 12\"/></svg>' +",
    "                        '<span>' + stepText + '工具执行成功: ' + escapeHtml(toolLabel(toolName)) + '</span><span class=\"tool-time\">' + formatEventClock() + '</span>';",
    "                }",
    "                if (resultText) {",
    "                    var out = matchedBlock.querySelector(\".tool-call-output.result\");",
    "                    if (!out) {",
    "                        out = document.createElement(\"div\");",
    "                        out.className = \"tool-call-output result compact-summary\";",
    "                        matchedBlock.appendChild(out);",
    "                    }",
    "                    out.textContent = resultText;",
    "                }",
    "                var cardId = matchedBlock.id;",
    "                if (!partial && activeToolCards.has(cardId)) activeToolCards.get(cardId).done = true;",
    "            } else {",
    "                var block = document.createElement(\"div\"); block.className = \"tool-call-log\"; block.dataset.toolName = toolName;",
    "                block.innerHTML = '<div class=\"tool-call-header success\">' +",
    "                    '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><polyline points=\"20 6 9 17 4 12\"/></svg>' +",
    "                    '<span>工具执行成功: ' + escapeHtml(toolName) + '</span><span class=\"tool-time\">' + formatEventClock() + '</span></div>';",
    "                if (resultText) block.innerHTML += '<div class=\"tool-call-output result compact-summary\">' + escapeHtml(resultText) + \"</div>\";",
    "                body.appendChild(block);",
    "            }",
    "            scrollToLatest();",
    "        }",
    "",
    "        /** 为特殊工具渲染富内容（diagnose 表格 / analyze+fix 问题卡片）到已创建的工具卡片中 */",
    "        function renderRichToolContent(skeleton, toolName, content, partial) {",
    "            var body = skeleton ? skeleton.thinkingBody : null;",
    "            if (!body) return;",
    "            var items = body.querySelectorAll(\".tool-call-log\");",
    "            var targetCard = null;",
    "            for (var i = items.length - 1; i >= 0; i--) { if (items[i].dataset.toolName === toolName) { targetCard = items[i]; break; } }",
    "            if (!targetCard) return;",
    "            var existingRichBody = targetCard.querySelector(\".tool-rich-body\");",
    "            if (existingRichBody) existingRichBody.remove();",
    "            var richBody = document.createElement(\"div\"); richBody.className = \"tool-rich-body\"; targetCard.appendChild(richBody);",
    "            if (toolName === \"diagnose\" || toolName === \"mirror_probe_deep\") renderDiagnoseRichContent(richBody, parseJsonPayload(content), !!partial);",
    "            else if (toolName === \"analyze\") { diagnosticState.analysis = parseJsonPayload(content); diagnosticState.fix = \"\"; renderDiagnosticRichContent(richBody); }",
    "            else if (toolName === \"fix\") { diagnosticState.fix = String(content || \"\"); renderDiagnosticRichContent(richBody); }",
    "            else { richBody.innerHTML = renderCollapsibleRawOutput(\"查看原始工具结果\", String(content || \"\")); }",
    "            scrollToLatest();",
    "        }",
    "",
    "        // ── 特殊工具：诊断（镜像检测表格） ──────────────────────────────",
    "        function renderDiagnoseRichContent(container, data, partial) {",
    "            var report = data && Array.isArray(data.report) ? data.report : [];",
    "            if (!report.length) {",
    "                container.innerHTML = '<div class=\"tool-empty\">正在等待镜像响应...</div>';",
    "                return;",
    "            }",
    "            function timingLabel(label, value) { return typeof value === \"number\" ? label + value + \"ms\" : \"\"; }",
    "            var rows = report.map(function(r) {",
    "                var latency = typeof r.latency_ms === \"number\" && r.latency_ms < 9999 ? r.latency_ms + \" ms\" : \"-\";",
    "                var shortHash = r.commit_hash ? escapeHtml(String(r.commit_hash).slice(0, 10)) : \"-\";",
    "                var method = r.method === \"sandbox_deep\" ? \"\\u6c99\\u7bb1\\u6df1\\u6d4b\" : r.method === \"sandbox\" ? \"\\u6c99\\u7bb1\" : \"\\u8fb9\\u7f18\";",
    "                var note = r.network_note || (r.sync_status === \"network_restricted\" ? \"当前检测节点无法取得官方基准，不代表官方源故障\" : \"\");",
    "                var details = [note, r.error ? \"检测详情: \" + r.error : \"\", r.commit_ref ? \"分支 \" + r.commit_ref.replace(\"refs/heads/\", \"\") : \"\", method, timingLabel(\"DNS \", r.dns_ms), timingLabel(\"TCP \", r.tcp_ms), timingLabel(\"TLS \", r.tls_ms), timingLabel(\"Git \", r.git_ms), r.ip ? \"IP \" + r.ip : \"\"].filter(Boolean).join(\" · \");",
    "                return '<div class=\"tool-row\">' +",
    "                    '<span class=\"tool-main\" title=\"' + escapeHtml(details || r.name || \"\") + '\"><strong>' + escapeHtml(r.name || \"Unknown\") + '</strong><span>' + escapeHtml(details) + '</span></span>' +",
    "                    '<span class=\"tool-mono\">' + latency + '</span>' +",
    "                    statusBadge(r.sync_status, !!r.error && r.sync_status !== \"network_restricted\") +",
    "                    '<span class=\"tool-mono tool-hide-sm\">' + (r.http_status || 0) + '</span>' +",
    "                    '<span class=\"tool-mono tool-hide-sm\">' + shortHash + '</span>' +",
    "                '</div>';",
    "            }).join(\"\");",
    "            container.innerHTML =",
    "                '<div class=\"tool-grid-head\"><span>镜像源</span><span>延迟</span><span>状态</span><span class=\"tool-hide-sm\">HTTP</span><span class=\"tool-hide-sm\">Commit</span></div>' +",
    "                rows +",
    "                (partial ? \"\" : '<button class=\"tool-copy-btn\" onclick=\"copyToolCardText(this)\">复制报告</button>');",
    "            container._sourceData = data;",
    "        }",
    "",
    "        // ── 特殊工具：环境诊断（问题卡片） ──────────────────────────────",
    "        function renderDiagnosticRichContent(container) {",
    "            var data = diagnosticState.analysis;",
    "            var issues = data && Array.isArray(data.issues) ? data.issues : [];",
    "            var parts = [];",
    "            if (data && data.doctor && data.doctor.assessment) {",
    "                var assessment = data.doctor.assessment;",
    "                parts.push('<div class=\"doctor-assessment\"><strong>先看对安装软件的影响</strong><dl class=\"impact-summary\"><dt>能安装软件吗？</dt><dd>' + escapeHtml(assessment.installation_impact || '目前信息不足，需要结合具体警告判断。') + '</dd><dt>现在需要处理吗？</dt><dd>' + escapeHtml(assessment.action_required || '先确认警告涉及的范围，再决定下一步。') + '</dd></dl></div>');",
    "            }",
    "            if (data && data.scope === \"provided_text\") parts.push('<p class=\"tool-empty\">仅分析已提供的报告，未检查或修改本机。</p>');",
    "            if (data && data.doctor && data.doctor.ready && !data.doctor.assessment) parts.push('<p>这份自检报告未记录警告，但未验证实际安装、网络或两端配置。</p>');",
    "            if (data && data.configuration) {",
    "                var comparison = data.configuration;",
    "                var configRows = (comparison.rows || []).map(function(row) {",
    "                    var value = function(v) { return escapeHtml(v === null ? '未提供或无法确认' : v === '' ? '空值（报告原值）' : String(v)); };",
    "                    var status = {same:'已提供值一致',different:'存在差异',incomplete:'证据不足'}[row.status] || '证据不足';",
    "                    return '<tr><th scope=\"row\">' + escapeHtml(row.label || row.key) + '<br><code>' + escapeHtml(row.key) + '</code></th><td>' + value(row.terminal) + '</td><td>' + value(row.desktop) + '</td><td>' + escapeHtml((row.candidate_sources || []).join('、') || '尚未定位') + '</td><td>' + status + '</td></tr>';",
    "                }).join('');",
    "                parts.push('<details class=\"diagnostic-section\"><summary class=\"diagnostic-section-title\">查看下载地址和技术细节</summary><div class=\"config-comparison\"><table><thead><tr><th>设置</th><th>终端报告</th><th>桌面报告</th><th>候选配置来源</th><th>结论</th></tr></thead><tbody>' + configRows + '</tbody></table></div><p class=\"tool-empty\">文件值匹配仅表示候选来源，未确认最终覆盖关系；缺少字段不代表未配置。</p></details>');",
    "            }",
    "            if (!data) {",
    "                parts.push('<div class=\"tool-empty\">正在分析环境信息...</div>');",
    "            } else if (!issues.length && !data.configuration && !(data.doctor && data.doctor.ready)) {",
    "                parts.push('<div class=\"diagnostic-section\"><div class=\"diagnostic-section-title\">结果</div><div class=\"tool-empty\">提供的文本未命中问题规则；这不等于已确认本机正常。</div></div>');",
    "            } else if (issues.length) {",
    "                var issueHtml = issues.map(function(issue) {",
    "                    var cls = issue.severity === \"error\" ? \"bad\" : issue.severity === \"warning\" ? \"warn\" : \"info\";",
    "                    return '<div class=\"issue-card\">' +",
    "                        '<div class=\"issue-title\"><span class=\"tool-badge ' + cls + '\">' + escapeHtml({error:\"需要检查\",warning:\"提醒\",info:\"说明\"}[issue.severity] || \"说明\") + '</span><strong>' + escapeHtml(issue.title || \"问题\") + '</strong></div>' +",
    "                        (issue.impact_scope || issue.installation_impact || issue.action_required ? '<dl class=\"impact-summary\"><dt>影响范围</dt><dd>' + escapeHtml(issue.impact_scope || '尚未确认') + '</dd><dt>安装软件</dt><dd>' + escapeHtml(issue.installation_impact || '尚未确认是否受影响') + '</dd><dt>是否需要处理</dt><dd>' + escapeHtml(issue.action_required || '需要更多信息再判断') + '</dd></dl>' : '') +",
    "                        '<p>' + escapeHtml(issue.message || \"\") + '</p><details class=\"issue-details\"><summary>查看原始提示与后续步骤</summary><p class=\"issue-suggest\">' + parseMarkdown(issue.suggestion || \"\") + '</p>' +",
    "                        (Array.isArray(issue.evidence) && issue.evidence.length ? '<p>报告线索：' + issue.evidence.map(escapeHtml).join('；') + '</p>' : '') +",
    "                        (Array.isArray(issue.commands) && issue.commands.length ? '<p>可先执行的查询命令（尚未执行）</p><pre class=\"command-box tool-command-box\"><code>' + escapeHtml(issue.commands.join('\\n')) + '</code></pre>' : '') +",
    "                        (issue.verification ? '<p class=\"issue-suggest\">复查：' + escapeHtml(issue.verification) + '</p>' : '') +",
    "                    '</details></div>';",
    "                }).join(\"\");",
    "                parts.push('<div class=\"diagnostic-section\"><div class=\"diagnostic-section-title\">问题</div>' + issueHtml + '</div>');",
    "            }",
    "            if (diagnosticState.fix) {",
    "                parts.push('<div class=\"diagnostic-section\"><div class=\"diagnostic-section-title\">修复命令</div><pre class=\"command-box tool-command-box\"><code>' + escapeHtml(diagnosticState.fix) + '</code></pre></div><button class=\"tool-copy-btn\" onclick=\"copyToolCardText(this)\">复制修复命令</button>');",
    "            } else if (data) {",
    "                parts.push(renderCollapsibleRawOutput(\"查看分析 JSON\", JSON.stringify(data, null, 2)) + '<button class=\"tool-copy-btn\" onclick=\"copyToolCardText(this)\">复制分析结果</button>');",
    "            }",
    "            container.innerHTML = parts.join(\"\");",
    "        }",
    "",
    "        function setStatus(text, skeleton) {",
    "            if(skeleton&&text&&skeleton.progressTitle.textContent!==text)skeleton.progressTitle.textContent=text;",
    "            if(!agentToolPanel)return;",
    "            agentToolPanel.textContent=text||(isGenerating?\"正在整理回复…\":\"Homebrew 助手\");",
    "            agentToolPanel.classList.toggle(\"running\",isGenerating);",
    "        }",
    "",
    "        function escapeHtml(text) {",
    "            var div = document.createElement(\"div\");",
    "            div.textContent = text;",
    "            return div.innerHTML;",
    "        }",
    "",
    "        function parseJsonPayload(value) {",
    "            if (!value) return null;",
    "            if (typeof value === \"object\") return value;",
    "            var cleaned = String(value).trim();",
    "            if (cleaned.startsWith(\"```\")) {",
    "                cleaned = cleaned.replace(/^```[a-zA-Z]*\\n/, \"\").replace(/\\n```$/, \"\").trim();",
    "            }",
    "            try { return JSON.parse(cleaned); } catch(e) { return null; }",
    "        }",
    "",
    "        function renderCollapsibleRawOutput(label, content) {",
    "            var text = String(content || \"\");",
    "            var lines = text ? text.split(/\\r?\\n/).length : 0;",
    "            var meta = lines > 1 ? \" · \" + lines + \" 行\" : \"\";",
    "            return '<details class=\"tool-raw-details\"><summary>' + escapeHtml(label + meta) + '</summary><pre class=\"tool-raw-output\">' + escapeHtml(text) + '</pre></details>';",
    "        }",
    "",
    "        function toolLabel(name) {",
    "            return name === \"intent_classify\" ? \"意图识别\" : name === \"diagnose\" || name === \"mirror_probe_deep\" ? \"在线镜像深度检测\" : name === \"formula_check\" ? \"软件包索引查询\" : name === \"analyze\" ? \"阅读你提供的信息\" : name === \"fix\" ? \"处理建议\" : name;",
    "        }",
    "",
    "        function statusBadge(status, hasError) {",
    "            if (status === \"network_restricted\") return '<span class=\"tool-badge warn\">检测受限</span>';",
    "            if (status === \"unverified\") return '<span class=\"tool-badge warn\">同步未验证</span>';",
    "            if (hasError || status === \"failed\") return '<span class=\"tool-badge bad\">检测失败</span>';",
    "            if (status === \"lagging\" || status === \"different\") return '<span class=\"tool-badge warn\">与上游不同</span>';",
    "            if (status === \"upstream\") return '<span class=\"tool-badge info\">官方源</span>';",
    "            return '<span class=\"tool-badge ok\">同步正常</span>';",
    "        }",
    "",
    "        function asNumber(value) {",
    "            var n = Number(value);",
    "            return Number.isFinite(n) && n >= 0 ? n : 0;",
    "        }",
    "",
    "        function formatTokenCount(value) {",
    "            return asNumber(value).toLocaleString(\"zh-CN\");",
    "        }",
    "",
    "        function renderUsage(event, skeleton) {",
    "            var target = skeleton && skeleton.usageEl ? skeleton.usageEl : activeUsageElement;",
    "            if (!target) return;",
    "            var input = asNumber(event.input_tokens || event.prompt_tokens || event.inputTokens);",
    "            var output = asNumber(event.output_tokens || event.completion_tokens || event.outputTokens);",
    "            var total = asNumber(event.total_tokens || event.totalTokens || (input + output));",
    "            var reasoning = asNumber(event.reasoning_tokens || event.reasoningTokens);",
    "            var cached = asNumber(event.cached_tokens || event.cachedTokens);",
    "            var parts = [",
    "                \"Token 用量 \" + formatTokenCount(total),",
    "                \"输入 \" + formatTokenCount(input),",
    "                \"输出 \" + formatTokenCount(output)",
    "            ];",
    "            if (reasoning) parts.push(\"思考 \" + formatTokenCount(reasoning));",
    "            if (cached) parts.push(\"缓存 \" + formatTokenCount(cached));",
    "            target.textContent = parts.join(\" · \");",
    "            target.style.display = \"\";",
    "            scrollToLatest();",
    "        }",
    "",
    "        /** 复制工具卡片中的数据 */",
    "        window.copyToolCardText = function(btn) {",
    "            var card = btn.closest(\".tool-call-log\");",
    "            if (!card) { var panel = btn.closest(\".tool-panel\"); if (panel) card = panel; }",
    "            if (!card) return;",
    "            var sourceEl = card.querySelector(\".tool-command-box\") || card.querySelector(\".tool-raw-output\") || card.querySelector(\".tool-call-output\");",
    "            var richBody=card.querySelector(\".tool-rich-body\");",
    "            var text = richBody&&richBody._sourceData ? JSON.stringify(richBody._sourceData,null,2) : sourceEl ? sourceEl.textContent : \"\";",
    "            if (!text) return;",
    "            copyText(text,btn);",
    "        };",
    "",
    "        async function sendMessage(overrideText, retryImages) {",
    "            if (isGenerating) return;",
    "            var imagesToSend = retryImages || pendingImages.slice();",
    "            var rawText = (overrideText || chatInput.value).trim();",
    "            if(packageQueryMode&&!overrideText&&!rawText){chatFeedback.textContent=\"请先输入软件包或应用名称。\";return;}",
    "            var text = packageQueryMode&&!overrideText ? \"查询软件包 \"+rawText : rawText || (imagesToSend.length ? \"请根据我粘贴的截图判断 Homebrew/BrewUI 问题\" : \"\");",
    "            if (!text) return;",
    "",
    "            isGenerating = true;",
    "            const request={controller:new AbortController(),reader:null,stopped:false,timedOut:false};",
    "            activeRequest=request;",
    "            updateSendState();",
    "            document.querySelectorAll(\".flag-btn,.retry-btn,[data-run-mirror]\").forEach(function(btn) { btn.disabled = true; });",
    "            const empty=document.getElementById(\"chat-empty\");if(empty)empty.hidden=true;",
    "            chatFeedback.textContent=\"\";",
    "",
    "            if (!overrideText) {",
    "                chatInput.value = \"\";",
    "                setPackageQueryMode(false);",
    "                resizeChatInput();",
    "            }",
    "            if(!retryImages)pendingImages = [];",
    "            renderAttachments();",
    "",
    "            // Append user message",
    "            var userMsgDiv = document.createElement(\"div\");",
    "            userMsgDiv.className = \"message user\";",
    "            var attachmentHtml = imagesToSend.length ? '<div class=\"message-attachments\">' + imagesToSend.map(function() { return '<span>粘贴的截图</span>'; }).join(\"\") + '</div>' : \"\";",
    "            userMsgDiv.innerHTML = escapeHtml(text) + attachmentHtml;",
    "            messagesContainer.appendChild(userMsgDiv);",
    "            scrollToLatest(true);",
    "",
    "            // 创建 Agent 回复骨架（avatar + 推理链容器 + 文本区）",
    "            var skeleton = createAgentSkeleton();",
    "            var presenter=createAnswerPresenter(skeleton.textContent,parseMarkdown,()=>scrollToLatest());request.presenter=presenter;",
    "            scrollToLatest();",
    "            activeAssistantMessage = skeleton.row;",
    "            activeTextContent = skeleton.textContent;",
    "            activeUsageElement = skeleton.usageEl;",
    "            activeToolCards.clear();",
    "            resetThinking();",
    "            resetGlobalToolPanel();",
    "            diagnosticState = { analysis: null, fix: \"\" };",
    "            var responseText = \"\";",
    "            var streamFinished = false;",
    "            var hasFinalToolResult = false;",
    "            var hasAnalysisResult = false;",
    "            var hasStreamError = false;",
    "            var suggestedActions = [];",
    "            var lastEventTime = Date.now();",
    "            var requestTimeout = null;",
    "            setStatus(\"请求已发送，等待服务响应...\", skeleton);",
    "            requestTimeout=setInterval(function(){",
    "                const idleMs=Date.now()-lastEventTime;",
    "                if(idleMs>12000)setStatus(\"仍在等待服务响应…\",skeleton);",
    "                if(idleMs>25000){request.timedOut=true;request.controller.abort();if(request.reader)request.reader.cancel().catch(()=>{});}",
    "            },1000);",
    "            ",
    "            try {",
    "                var images = await Promise.all(imagesToSend.map(readImageAsBase64));",
    "                request.controller.signal.throwIfAborted();",
    "                var response = await fetch(\"/chat\", {",
    "                    method: \"POST\",",
    "                    headers: {",
    "                        \"Content-Type\": \"application/json\",",
    "                        \"makers-conversation-id\": convId",
    "                    },",
    "                    body: JSON.stringify({ message: text, images: images }),",
    "                    signal: request.controller.signal",
    "                });",
    "",
    "                if (!response.ok) {",
    "                    var errorText = \"\";",
    "                    try {",
    "                        var errorPayload = await response.json();",
    "                        errorText = errorPayload && (errorPayload.error || errorPayload.message) ? (errorPayload.error || errorPayload.message) : \"\";",
    "                    } catch (e) {",
    "                        try { errorText = await response.text(); } catch (_) {}",
    "                    }",
    "                    throw new Error(errorText || (\"HTTP \" + response.status));",
    "                }",
    "                setStatus(\"服务已连接，等待模型首条输出...\", skeleton);",
    "",
    "                var reader = response.body.getReader();",
    "                request.reader=reader;",
    "                var decoder = new TextDecoder();",
    "                var buffer = \"\";",
    "",
    "",
    "                while (!streamFinished) {",
    "                    var _ref = await reader.read();",
    "                    var done = _ref.done;",
    "                    var value = _ref.value;",
    "                    request.controller.signal.throwIfAborted();",
    "                    if (done) break;",
    "                    lastEventTime = Date.now();",
    "",
    "                    buffer += decoder.decode(value, { stream: true });",
    "                    var lines = buffer.split(\"\\n\");",
    "                    buffer = lines.pop() || \"\";",
    "                    for (var li = 0; li < lines.length; li++) {",
    "                        var trimmed = lines[li].trim();",
    "                        if (!trimmed || !trimmed.startsWith(\"data:\")) continue;",
    "                        var payloadStr = trimmed.slice(5).trim();",
    "                        if (payloadStr === \"[DONE]\") {",
    "                            streamFinished = true;",
    "                            break;",
    "                        }",
    "",
    "                        try {",
    "                            var event = JSON.parse(payloadStr);",
    "                            ",
    "                            if (event.type === \"ping\") {",
    "                                continue;",
    "                            }",
    "                            ",
    "                            if(event.type===\"reasoning\"){handleReasoningEvent(skeleton,event);continue;}",
    "                            if (event.type === \"thinking\" || event.type === \"thinking_summary\") {",
    "                                if (event.content === null || event.content === undefined) continue;",
    "                                var rawThinkingContent = String(event.content);",
    "                                if (/意图识别|intent_classify/.test(rawThinkingContent)) rawThinkingContent = \"正在阅读你的问题…\";",
    "                                var contentTrimmed = rawThinkingContent.trim();",
    "                                if (contentTrimmed) {",
    "                                    setStatus(contentTrimmed.length<50?contentTrimmed:\"正在处理问题…\", skeleton);",
    "                                    handleThinkingEvent(skeleton, rawThinkingContent);",
    "                                }",
    "                                currentToolName = \"\";",
    "                            } else if (event.type === \"tool_call\") {",
    "                                if (event.name === \"intent_classify\") { currentToolName = event.name; continue; }",
    "                                currentToolName = event.name;",
    "                                handleToolCallEvent(skeleton, event.name, event.arguments);",
    "                                setStatus(\"正在执行：\" + toolLabel(event.name), skeleton);",
    "                            } else if (event.type === \"tool_result\") {",
    "                                var resultName = event.name || currentToolName || \"tool\";",
    "                                if (resultName === \"intent_classify\") { currentToolName = \"\"; continue; }",
    "                                if (!event.partial && resultName !== \"intent_classify\") hasFinalToolResult = true;",
    "                                if (!event.partial && resultName === \"analyze\") hasAnalysisResult = true;",
    "                                // 先生成摘要文本写入 output 框",
    "                                var summaryText = formatToolSummary(resultName, event.content);",
    "                                handleToolResultEvent(skeleton, resultName, summaryText, !!event.partial);",
    "                                // 对特殊工具追加富内容渲染",
    "                                if (resultName === \"diagnose\" || resultName === \"mirror_probe_deep\" || resultName === \"analyze\" || resultName === \"fix\" || resultName === \"formula_check\") { renderRichToolContent(skeleton, resultName, event.content, event.partial); }",
    "                                if (!event.partial) {",
    "                                    setStatus(\"正在整理结果…\", skeleton);",
    "                                    currentToolName = \"\";",
    "                                }",
    "                            } else if (event.type === \"ai_response\") {",
    "                                if(hasStreamError)continue;",
    "                                if(!responseText.trim()&&!skeleton.reasoningText&&!skeleton.thinkingWrapper.dataset.userToggled)skeleton.thinkingWrapper.open=false;",
    "                                responseText += (event.content || \"\");",
    "                                setStatus(\"正在生成回复…\",skeleton);presenter.append(event.content||\"\");",
    "                            } else if (event.type === \"suggest_actions\") {",
    "                                if (!hasStreamError) suggestedActions = normalizeSuggestedActions(event.actions);",
    "                            } else if (event.type === \"usage\") {",
    "                                renderUsage(event, skeleton);",
    "                            } else if (event.type === \"error_message\") {",
    "                                hasStreamError = true;",
    "                                presenter.cancel();skeleton.textContent.hidden=false;",
    "                                skeleton.textContent.textContent=\"本次请求未能完成：\"+String(event.content||\"服务异常\");",
    "                                setStatus(null, skeleton);",
    "                                var errorDiv = document.createElement(\"div\"); errorDiv.className = \"tool-call-log\";",
    "                                errorDiv.innerHTML = '<div class=\"tool-call-header\" style=\"color:#ef4444\">' + '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M15 9l-6 6M9 9l6 6\"/></svg>' + '<span>错误: ' + escapeHtml(event.content) + \"</span></div>\";",
    "                                if (skeleton && skeleton.thinkingBody) skeleton.thinkingBody.appendChild(errorDiv); else messagesContainer.appendChild(errorDiv);",
    "                                scrollToLatest();",
    "                            }",
    "                        } catch (e) {",
    "                            console.error(\"Error parsing SSE line:\", e);",
    "                        }",
    "                    }",
    "                }",
    "                ",
    "                if (streamFinished) await reader.cancel();",
    "                setStatus(null, skeleton);",
    "",
    "            } catch (err) {",
    "                if (requestTimeout) { clearInterval(requestTimeout); requestTimeout = null; }",
    "                setStatus(null, skeleton);",
    "                if(!request.stopped){presenter.cancel();hasStreamError=true;skeleton.textContent.textContent=request.timedOut?\"请求超时，请重试。\":(err&&err.message?err.message:\"连接失败，请重试。\");}",
    "            } finally {",
    "                if (requestTimeout) { clearInterval(requestTimeout); requestTimeout = null; }",
    "                if(request.reader)await request.reader.cancel().catch(()=>{});",
    "                skeleton.finishedAt=Date.now();clearInterval(skeleton.progressTimer);",
    "                if(hasStreamError)presenter.cancel();else if(request.stopped){presenter.flush();presenter.cancel();}else await presenter.finish();",
    "                if(request.stopped){if(!responseText.trim())skeleton.textContent.textContent=\"已停止生成。\";chatFeedback.textContent=\"已停止生成，已收到的内容已保留。\";}",
    "                if (skeleton.textContent.querySelector(\".typing-indicator\")) {",
    "                    skeleton.textContent.textContent = hasStreamError ? \"本次请求未能完成，请查看处理详情。\" : hasFinalToolResult ? \"已完成，结果见处理详情。\" : \"服务已结束，但未返回回复，请重试。\";",
    "                }",
    "                isGenerating = false;",
    "                activeRequest=null;",
    "                setStatus(null,skeleton);",
    "                chatInput.disabled = false;",
    "                skeleton.textContent.hidden=false;",
    "                finishProgress(skeleton,{stopped:request.stopped,failed:hasStreamError||(!responseText.trim()&&!hasFinalToolResult&&!request.stopped),keepOpen:hasFinalToolResult&&!responseText.trim()});",
    "                if(!request.stopped&&(hasStreamError||(!responseText.trim()&&!hasFinalToolResult)))addRetry(skeleton,text,imagesToSend);",
    "                if(streamFinished&&!request.stopped&&!hasStreamError&&(responseText.trim()||hasFinalToolResult))renderSuggestedActions(skeleton,suggestedActions);",
    "                if(streamFinished&&!request.stopped&&!hasStreamError&&hasAnalysisResult&&responseText.trim())revealDiagnosticAnswer(skeleton);",
    "                updateSendState();",
    "                document.querySelectorAll(\".flag-btn,.retry-btn,[data-run-mirror]\").forEach(function(btn) { btn.disabled = false; });",
    "            }",
    "        }",
    "",
    "        /** 将工具结果格式化为简短摘要文本（显示在灰色 output 框中） */",
    "        function formatToolSummary(toolName, rawContent) {",
    "            if (!rawContent) return \"\";",
    "            if (toolName === \"intent_classify\") {",
    "                try {",
    "                    var intent = typeof rawContent === \"string\" ? JSON.parse(rawContent) : rawContent;",
    "                    var scope = intent.is_homebrew_related ? \"Homebrew 相关\" : \"非 Homebrew 相关\";",
    "                    var routeLabels = { model_identity: \"\\u8eab\\u4efd\\u8bf4\\u660e\", restore_official: \"\\u6062\\u590d\\u5b98\\u65b9\\u6e90\", mirror_probe_deep: \"\\u955c\\u50cf\\u6df1\\u5ea6\\u68c0\\u6d4b\", formula_check: \"\\u8f6f\\u4ef6\\u5305\\u7d22\\u5f15\\u67e5\\u8be2\", brew_missing: \"brew PATH \\u6392\\u67e5\", analysis_fix: \"\\u7ec8\\u7aef\\u65e5\\u5fd7\\u5206\\u6790\", general_homebrew: \"\\u5e38\\u89c4 Homebrew \\u56de\\u7b54\", reject: \"\\u62d2\\u7b54\" };",
    "                    return scope + \"\\uff0c下一步: \" + (routeLabels[intent.route] || intent.route) + \"\\u3002\";",
    "                } catch(e) { return String(rawContent).slice(0, 200); }",
    "            }",
    "            if (toolName === \"diagnose\" || toolName === \"mirror_probe_deep\") {",
    "                try {",
    "                    var data = typeof rawContent === \"string\" ? JSON.parse(rawContent) : rawContent;",
    "                    var report = data.report || [];",
    "                    var availableMirrors = report.filter(function(r) { return !r.error && r.commit_hash && (r.git_ok || (r.http_status >= 200 && r.http_status < 400)) && r.name !== \"Official (\\u5b98\\u65b9\\u6e90)\"; });",
    "                    var officialRestricted = report.some(function(r) { return r.sync_status === \"network_restricted\"; });",
    "                    var best = availableMirrors.slice().sort(function(a,b) { return (a.sync_status === \"synced\" ? 0 : 1) - (b.sync_status === \"synced\" ? 0 : 1) || a.latency_ms - b.latency_ms; })[0];",
    "                    var parts = [\"\\u68c0\\u6d4b\\u5230 \" + report.length + \" \\u4e2a\\u6e90\"];",
    "                    if (availableMirrors.length > 0) parts.push(availableMirrors.length + \" \\u4e2a\\u955c\\u50cf\\u53ef\\u7528\");",
    "                    if (officialRestricted) parts.push(\"官方源访问受限\");",
    "                    if (best) parts.push(\"\\u6700\\u4f73: \" + best.name + \" (\" + best.latency_ms + \"ms)\");",
    "                    if (data.duration_ms) parts.push(\"\\u8017\\u65f6: \" + (data.duration_ms / 1000).toFixed(1) + \"s\");",
    "                    return parts.join(\"\\uff0c \") + \"\\u3002\";",
    "                } catch(e) { return String(rawContent).slice(0, 200); }",
    "            }",
    "            if (toolName === \"analyze\") {",
    "                try {",
    "                    var d = typeof rawContent === \"string\" ? JSON.parse(rawContent) : rawContent;",
    "                    var issues = d.issues || [];",
    "                    if (d.doctor && d.doctor.assessment) return [d.doctor.assessment.installation_impact, d.doctor.assessment.action_required].filter(Boolean).join(' ');",
    "                    if (d.doctor && d.doctor.ready) return '这份 Doctor 报告未记录警告，尚未验证网络或两端配置。';",
    "                    if (d.configuration && !issues.length) return '已对照 ' + (d.configuration.rows || []).length + ' 项已提供的值；详情见对照表。';",
    "                    if (!issues.length) return '提供的文本未匹配已知问题，尚未确认本机状态。';",
    "                    return \"\\u53d1\\u73b0 \" + issues.length + \" \\u4e2a\\u95ee\\u9898\\uff08\" + issues.filter(function(i){return i.severity===\"error\"}).length + \" \\u4e2a\\u9519\\u8bef/\" + issues.filter(function(i){return i.severity===\"warning\"}).length + \" \\u4e2a\\u8b66\\u544a\\uff09\\u3002\";",
    "                } catch(e) { return String(rawContent).slice(0, 200); }",
    "            }",
    "            if (toolName === \"fix\") {",
    "                return \"\\u5df2\\u751f\\u6210\\u4fee\\u590d\\u547d\\u4ee4\\u3002\";",
    "            }",
    "            if (toolName === \"formula_check\") {",
    "                try {",
    "                    var f = typeof rawContent === \"string\" ? JSON.parse(rawContent) : rawContent;",
    "                    if (f.partial || f.source === \"pending\") return \"\\u6b63\\u5728\\u67e5\\u8be2 Homebrew JSON \\u7d22\\u5f15: \" + (f.query || \"\") + \"...\";",
    "                    var best = f.exact || (f.candidates || [])[0];",
    "                    if (!best) return \"\\u672a\\u5728 Homebrew JSON \\u7d22\\u5f15\\u4e2d\\u627e\\u5230\\u660e\\u786e\\u5339\\u914d\\u3002\";",
    "                    return \"\\u547d\\u4e2d \" + best.type + \": \" + best.token + \"\\uff0c\\u547d\\u4ee4: \" + best.install_command;",
    "                } catch(e) { return String(rawContent).slice(0, 200); }",
    "            }",
    "            // 默认截断",
    "            var s = String(rawContent);",
    "            return s.length > 200 ? s.slice(0, 200) + \"...\" : s;",
    "        }",
    "",
    "        function loadHtml2Canvas() {",
    "            return new Promise((resolve, reject) => {",
    "                if (window.html2canvas) {",
    "                    resolve(window.html2canvas);",
    "                    return;",
    "                }",
    "                const script = document.createElement(\"script\");",
    "                script.src = \"https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js\";",
    "                script.onload = () => resolve(window.html2canvas);",
    "                script.onerror = () => reject(new Error(\"Failed to load html2canvas\"));",
    "                document.head.appendChild(script);",
    "            });",
    "        }",
    "",
    "        window.shareConversation = async function() {",
    "            const btn = document.querySelector(\".chat-share-btn\");",
    "            let shareWrapper;",
    "            if (btn) {",
    "                btn.disabled = true;",
    "                btn.innerHTML = '<span class=\"spin-loader\"></span>';",
    "            }",
    "            try {",
    "                const isLight = document.documentElement.getAttribute('data-theme') === 'light';",
    "                const html2canvas = await loadHtml2Canvas();",
    "                shareWrapper = document.createElement(\"div\");",
    "                shareWrapper.className = isLight ? \"share-export-light\" : \"share-export-dark\";",
    "                shareWrapper.style.position = \"absolute\";",
    "                shareWrapper.style.left = \"-9999px\";",
    "                shareWrapper.style.width = \"720px\";",
    "                shareWrapper.style.background = isLight ? \"#f6f7f8\" : \"#141517\";",
    "                shareWrapper.style.padding = \"40px\";",
    "                shareWrapper.style.boxSizing = \"border-box\";",
    "                ",
    "                const exportStyle = document.createElement(\"style\");",
    "                exportStyle.textContent = isLight ? \".share-export-light,.share-export-light *{opacity:1!important;text-shadow:none!important}.share-export-light .message,.share-export-light .agent-text-content,.share-export-light .thinking-content,.share-export-light .tool-call-output,.share-export-light .tool-raw-output,.share-export-light .tool-command-box{color:#25272b!important}.share-export-light .message.system,.share-export-light .agent-text-content{background:#ffffff!important;border-color:#dce0e4!important}.share-export-light .message.system strong,.share-export-light .agent-text-content strong{color:#b94713!important}.share-export-light .message.user{background:#fff0e8!important;border-color:#dce0e4!important;color:#b94713!important}.share-export-light .agent-avatar{background:#fff0e8!important;border-color:#dce0e4!important;color:#b94713!important}.share-export-light .thinking-wrapper{background:#ffffff!important;border-color:#dce0e4!important}.share-export-light .thinking-header{background:#eff1f3!important;border-bottom-color:#dce0e4!important;color:#626771!important}.share-export-light .thinking-content{background:#f2f4f5!important;border-bottom-color:#dce0e4!important}.share-export-light .tool-call-log{background:#ffffff!important;border-color:#dce0e4!important}.share-export-light .tool-call-header.running{background:#fff0e8!important;color:#b94713!important}.share-export-light .tool-call-header.success{background:#edf8f0!important;color:#218653!important}.share-export-light .tool-time,.share-export-light .tool-call-args summary,.share-export-light .tool-main span,.share-export-light .tool-mono,.share-export-light .agent-usage{color:#626771!important}.share-export-light .tool-call-output,.share-export-light .tool-raw-output,.share-export-light .command-box{background:#f2f4f5!important;border-color:#dce0e4!important;color:#25272b!important}.share-export-light code{color:#b94713!important}.share-export-light .agent-usage{border-top-color:#dce0e4!important}.share-export-light .tool-rich-body{background:#f2f4f5!important;border-top-color:#dce0e4!important}.share-export-light .tool-grid-head{background:#eff1f3!important;color:#25272b!important}.share-export-light .tool-row{border-bottom-color:#dce0e4!important}.share-export-light .tool-main{color:#25272b!important}\" : \"\";",
    "                shareWrapper.appendChild(exportStyle);",
    "                ",
    "                const terminalCard = document.createElement(\"div\");",
    "                terminalCard.style.background = isLight ? \"#ffffff\" : \"#141517\";",
    "                terminalCard.style.border = isLight",
    "                    ? \"1px solid #dce0e4\"",
    "                    : \"1px solid #363a40\";",
    "                terminalCard.style.borderRadius = \"8px\";",
    "                terminalCard.style.boxShadow = isLight",
    "                    ? \"0 24px 60px #0000000a\"",
    "                    : \"0 24px 60px rgba(0,0,0,0.5)\";",
    "                terminalCard.style.overflow = \"hidden\";",
    "                terminalCard.style.display = \"flex\";",
    "                terminalCard.style.flexDirection = \"column\";",
    "                ",
    "                const header = document.createElement(\"div\");",
    "                header.className = \"terminal-header\";",
    "                header.style.background = isLight ? \"#eff1f3\" : \"#24272b\";",
    "                header.style.borderBottom = isLight",
    "                    ? \"1px solid #dce0e4\"",
    "                    : \"1px solid #363a40\";",
    "                header.style.padding = \"14px 24px\";",
    "                header.style.display = \"flex\";",
    "                header.style.alignItems = \"center\";",
    "                ",
    "                const headerTextColor = isLight ? \"#25272b\" : \"#f0f1f3\";",
    "                header.innerHTML = '<div class=\"terminal-dots\" style=\"display:flex;gap:6px\"><span class=\"dot red\" style=\"width:10px;height:10px;background:#ff5f56;border-radius:50%\"></span><span class=\"dot yellow\" style=\"width:10px;height:10px;background:#ffbd2e;border-radius:50%\"></span><span class=\"dot green\" style=\"width:10px;height:10px;background:#27c93f;border-radius:50%\"></span></div><div style=\"margin:0 auto;color:' + headerTextColor + ';font-size:0.85rem;font-family:var(--font-mono);font-weight:700\">brew-ai @ homebrew-cn</div>';",
    "                terminalCard.appendChild(header);",
    "                ",
    "                const messagesClone = messagesContainer.cloneNode(true);",
    "                messagesClone.removeAttribute(\"id\");messagesClone.querySelectorAll(\"[id]\").forEach(el=>el.removeAttribute(\"id\"));",
    "                messagesClone.querySelectorAll(\".chat-empty,.help-guide,.answer-followups,.retry-btn,.code-copy-btn,.tool-copy-btn\").forEach(el=>el.remove());",
    "                messagesClone.querySelectorAll(\".thinking-wrapper:not([open])\").forEach(el=>el.remove());",
    "                messagesClone.querySelectorAll(\"pre,pre code,.thinking-content,.tool-call-output,.tool-raw-output\").forEach(el=>{el.style.maxHeight=\"none\";el.style.whiteSpace=\"pre-wrap\";el.style.overflowWrap=\"anywhere\";el.style.overflow=\"visible\";});",
    "                messagesClone.style.height = \"auto\";",
    "                messagesClone.style.maxHeight = \"none\";",
    "                messagesClone.style.overflow = \"visible\";",
    "                messagesClone.style.background = \"transparent\";",
    "                messagesClone.style.padding = \"30px\";",
    "                ",
    "                const lastMsg = messagesClone.lastElementChild;",
    "                if (lastMsg) {",
    "                    const indicator = lastMsg.querySelector(\".typing-indicator\");",
    "                    if (indicator && indicator.parentElement) {",
    "                        indicator.parentElement.innerHTML = \"<em>正在输入...</em>\";",
    "                    }",
    "                }",
    "                terminalCard.appendChild(messagesClone);",
    "                ",
    "                const footer = document.createElement(\"div\");",
    "                footer.style.background = isLight ? \"#eff1f3\" : \"#24272b\";",
    "                footer.style.borderTop = isLight",
    "                    ? \"1px solid #dce0e4\"",
    "                    : \"1px solid #363a40\";",
    "                footer.style.padding = \"20px 30px\";",
    "                footer.style.display = \"flex\";",
    "                footer.style.justifyContent = \"space-between\";",
    "                footer.style.alignItems = \"center\";",
    "                ",
    "                const titleColor = isLight ? \"#25272b\" : \"#f0f1f3\";",
    "                const subColor = isLight ? \"#626771\" : \"#abb0b9\";",
    "                ",
    "                footer.innerHTML = '<div style=\"display:flex;align-items:center;gap:12px\"><span style=\"font-size:1.6rem\">🍺</span><div style=\"display:flex;flex-direction:column;gap:3px\"><span style=\"font-weight:700;font-size:0.85rem;color:' + titleColor + '\">Homebrew CN 智能助手</span><span style=\"font-size:0.72rem;color:' + subColor + '\">极速安装 · 镜像检测 · 环境诊断</span></div></div><div style=\"font-family:var(--font-mono);font-weight:700;font-size:0.85rem;color:var(--accent)\">brew-cn.mintimate.cn</div>';",
    "                terminalCard.appendChild(footer);",
    "                ",
    "                shareWrapper.appendChild(terminalCard);",
    "                document.body.appendChild(shareWrapper);",
    "                ",
    "                const canvas = await html2canvas(shareWrapper, {",
    "                    backgroundColor: isLight ? \"#f6f7f8\" : \"#141517\",",
    "                    scale: 2,",
    "                    useCORS: true,",
    "                    logging: false",
    "                });",
    "                ",
    "                const link = document.createElement(\"a\");",
    "                link.download = \"brew-ai-share-\" + Date.now() + \".png\";",
    "                link.href = canvas.toDataURL(\"image/png\");",
    "                link.click();",
    "                ",
    "            } catch (e) {",
    "                console.error(\"生成分享图片失败:\", e);",
    "                chatFeedback.textContent=\"生成分享图片失败，请重试。\";",
    "            } finally {",
    "                if(shareWrapper)shareWrapper.remove();",
    "                if (btn) {",
    "                    btn.disabled = false;",
    "                    btn.innerHTML = UI_ICONS.Download;",
    "                }",
    "            }",
    "        };",
    "    })();",
    "</script>",
  ];
  return '\n    ' + lines.join('\n');
}
