// 客户端 JavaScript 模板
// 使用数组 join 方式返回 script 标签，避免模板字符串嵌套问题
export function getClientScript() {
  const lines = [
    '<script>',
    '    const {host,protocol}=window.location;',
    "    let baseUrl='https://brew-cn.mintimate.cn';",
    "    if(host&&!/localhost|127\\.0\\.0\\.1/.test(host)&&protocol!=='file:') baseUrl=protocol+'//'+host;",
    '',
    '    // Update macOS commands',
    '    const macInstall=document.getElementById(\'install-command-macos\');',
    '    const macUninstall=document.getElementById(\'uninstall-command-macos\');',
    '    if(macInstall) macInstall.textContent=\'/bin/zsh -c "$\'+\'(curl -fsSL \'+baseUrl+\'/install)"\';',
    '    if(macUninstall) macUninstall.textContent=\'/bin/zsh -c "$\'+\'(curl -fsSL \'+baseUrl+\'/install)" -- --uninstall\';',    '',
    '    // Update Linux commands',
    '    const linInstall=document.getElementById(\'install-command-linux\');',
    '    const linUninstall=document.getElementById(\'uninstall-command-linux\');',
    '    if(linInstall) linInstall.textContent=\'/bin/bash -c \"$\'+\'(curl -fsSL \'+baseUrl+\'/install)\"\';',
    '    if(linUninstall) linUninstall.textContent=\'/bin/bash -c \"$\'+\'(curl -fsSL \'+baseUrl+\'/install)\" -- --uninstall\';',
    '',
    '    // OS tab switching',
    '    window.switchOS=function(os){',
    '        document.querySelectorAll(\'.os-tab\').forEach(t=>{t.classList.toggle(\'active\',t.dataset.os===os)});',
    '        document.querySelectorAll(\'.os-panel\').forEach(p=>{p.style.display=\'none\'});',
    '        const panel=document.getElementById(\'os-\'+os);',
    '        if(panel) panel.style.display=\'block\';',
    '    };',
    '',
    '    // Auto-detect OS from User-Agent',
    '    (function(){',
    '        const ua=navigator.userAgent||navigator.platform||\'\';',
    '        if(/Linux/i.test(ua)&&!/Android/i.test(ua)) switchOS(\'linux\');',
    '    })();',
    '',
    '    function copyCommand(id,btn){',
    '        const text=document.getElementById(id).textContent,orig=btn.textContent;',
    "        const done=()=>{btn.textContent='已复制!';btn.classList.add('copied');setTimeout(()=>{btn.textContent=orig;btn.classList.remove('copied')},2000)};",
    "        if(navigator.clipboard){navigator.clipboard.writeText(text).then(done).catch(done)}else{const t=document.createElement('textarea');t.value=text;t.style.cssText='position:fixed;opacity:0';document.body.appendChild(t);t.select();document.execCommand('copy');document.body.removeChild(t);done()}",
    '    }',
    '',
    '    const THEME_KEY=\'brew-cn-theme\';',
    '    const mediaDark=window.matchMedia(\'(prefers-color-scheme: dark)\');',
    '    const THEME_MODES=[\'light\',\'system\',\'dark\'];',
    '    function getSavedThemeMode(){',
    '        const saved=localStorage.getItem(THEME_KEY);',
    '        return THEME_MODES.includes(saved)?saved:\'system\';',
    '    }',
    '    function resolveTheme(mode){',
    '        return mode===\'system\'?(mediaDark.matches?\'dark\':\'light\'):mode;',
    '    }',
    '    function getModeLabel(mode){',
    '        return mode===\'light\'?\'亮色\':mode===\'dark\'?\'暗色\':\'跟随系统\';',
    '    }',
    '    function applyThemeMode(mode,{persist=false}={}){',
    '        const resolved=resolveTheme(mode);',
    '        document.documentElement.setAttribute(\'data-theme\',resolved);',
    '        const toggle=document.getElementById(\'theme-toggle\');',
    '        if(toggle){',
    '            toggle.dataset.theme=mode;',
    '            toggle.setAttribute(\'aria-label\',\'切换主题（当前\'+getModeLabel(mode)+\'）\');',
    '            toggle.setAttribute(\'title\',\'当前：\'+getModeLabel(mode)+\'（点击切换）\');',
    '        }',
    '        if(persist) localStorage.setItem(THEME_KEY,mode);',
    '    }',
    '    function nextThemeMode(current){',
    '        const idx=THEME_MODES.indexOf(current);',
    '        return THEME_MODES[(idx+1)%THEME_MODES.length];',
    '    }',
    '    function setupThemeToggle(){',
    '        applyThemeMode(getSavedThemeMode());',
    '        const toggle=document.getElementById(\'theme-toggle\');',
    '        if(toggle){',
    '            toggle.addEventListener(\'click\',()=>{',
    '                const current=toggle.dataset.theme||getSavedThemeMode();',
    '                applyThemeMode(nextThemeMode(current),{persist:true});',
    '            });',
    '        }',
    '        const handleChange=()=>{',
    '            if(getSavedThemeMode()===\'system\') applyThemeMode(\'system\');',
    '        };',
    '        if(mediaDark.addEventListener) mediaDark.addEventListener(\'change\',handleChange);',
    '        else if(mediaDark.addListener) mediaDark.addListener(handleChange);',
    '    }',
    '',
    '    const fu=v=>v&&!/unknown/i.test(v)?v:\'\';',
    '    function timeAgo(t){const d=new Date(t),ms=Date.now()-d,m=ms/6e4|0,h=ms/36e5|0,dy=ms/864e5|0;return m<1?\'刚刚\':m<60?m+\'分钟前\':h<24?h+\'小时前\':dy<30?dy+\'天前\':d.toLocaleDateString(\'zh-CN\')}',
    '    const INITIAL_SHOW=10;',
    '    let allInstalls=[];',
    '    function renderRecentInstalls(installs){',
    "        const c=document.getElementById('recent-installs');",
    '        if(!installs||!installs.length){c.innerHTML=\'<div style="text-align:center;color:var(--text-muted);font-size:.9rem;padding:16px 0">暂无安装记录</div>\';return}',
    '        allInstalls=installs;',
    '        renderInstallList(INITIAL_SHOW);',
    '    }',
    '    function renderInstallItem(i){',
    "        const loc=[fu(i.city),fu(i.region),fu(i.country)].filter(Boolean).join(', ')||'未知地区';",
    "        const cls=i.active===false?'is-offline':'is-online';",
    "        return '<div class=\"recent-item '+cls+'\"><span class=\"ri-icon\">📍</span><span class=\"ri-location\" title=\"'+loc+'\">'+loc+'</span><span class=\"ri-ip\">'+(i.ip||'')+'</span><span class=\"ri-time\">'+timeAgo(i.time)+'</span></div>'",
    '    }',
    '    function renderInstallList(count){',
    "        const c=document.getElementById('recent-installs');",
    '        const showing=allInstalls.slice(0,count);',
    "        let html=showing.map(renderInstallItem).join('');",
    '        if(count<allInstalls.length){',
    "            html+='<button class=\"recent-toggle-btn\" onclick=\"expandInstalls()\">展开更多（共 '+allInstalls.length+' 条）</button>'",
    '        }else if(allInstalls.length>INITIAL_SHOW){',
    "            html+='<button class=\"recent-toggle-btn\" onclick=\"collapseInstalls()\">收起</button>'",
    '        }',
    '        c.innerHTML=html;',
    '    }',
    '    window.expandInstalls=function(){renderInstallList(allInstalls.length)};',
    '    window.collapseInstalls=function(){renderInstallList(INITIAL_SHOW);document.getElementById("recent-installs").scrollIntoView({behavior:"smooth",block:"start"})};',
    '',
    '    async function fetchStats(){',
    '        try{',
    "            const r=await(await fetch('/api/stats')).json();",
    '            if(r.code!==0)return;',
    "            document.getElementById('total-calls').textContent=r.data.totalCalls.toLocaleString();",
    '            const t=r.data.lastCallTime;',
    "            if(!t){document.getElementById('last-call').textContent='暂无记录';return}",
    "            const el=document.getElementById('last-call');el.textContent=timeAgo(t);el.title=new Date(t).toLocaleString('zh-CN');",
    '            renderRecentInstalls(r.data.recentInstalls||[]);',
    "        }catch(e){console.error('fetchStats:',e)}",
    '    }',
    '',
    "    document.addEventListener('DOMContentLoaded',()=>{",
    '        setupThemeToggle();',
    '        fetchStats();setInterval(fetchStats,3e4);',
    "        const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('active');ob.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -50px 0px'});",
    "        document.querySelectorAll('.reveal').forEach(el=>ob.observe(el));",
    '',
    '',
    '        // 🎉 隐藏彩蛋：连续输入 brew 显示腾讯云镜像源',
    "        let eggBuf='',eggTimer=null;",
    "        document.addEventListener('keydown',function(e){",
    "            if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;",
    "            clearTimeout(eggTimer);",
    "            eggBuf+=e.key.toLowerCase();",
    "            eggTimer=setTimeout(()=>{eggBuf=''},2000);",
    "            if(eggBuf.includes('brew')){",
    "                eggBuf='';",
    "                const row=document.getElementById('mirror-egg');",
    "                if(row&&!row.classList.contains('egg-show')){",
    "                    row.classList.add('egg-show');",
    "                    row.scrollIntoView({behavior:'smooth',block:'center'});",
    '                }',
    '            }',
    '        });',
    '    });',
    '',
    '    // === AI Chat Agent Client Logic ===',
    '    (function() {',
    '        const toggleBtn = document.getElementById("ai-chat-toggle");',
    '        const closeBtn = document.getElementById("ai-chat-close");',
    '        const chatWindow = document.getElementById("ai-chat-window");',
    '        const chatInput = document.getElementById("chat-input");',
    '        const sendBtn = document.getElementById("chat-send-btn");',
    '        const messagesContainer = document.getElementById("chat-messages");',
    '',
    '        if (!toggleBtn) return;',
    '',
    '        // Generate or retrieve conversation ID',
    '        let convId = localStorage.getItem("homebrew-cn-conv-id");',
    '        if (!convId) {',
    '            convId = "conv_" + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);',
    '            localStorage.setItem("homebrew-cn-conv-id", convId);',
    '        }',
    '',
    '        // Toggle chat window',
    '        toggleBtn.addEventListener("click", () => {',
    '            if (chatWindow.style.display === "none") {',
    '                chatWindow.style.display = "flex";',
    '                chatInput.focus();',
    '                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '            } else {',
    '                chatWindow.style.display = "none";',
    '            }',
    '        });',
    '',
    '        closeBtn.addEventListener("click", () => {',
    '            chatWindow.style.display = "none";',
    '        });',
    '',
    '        // Input button state',
    '        chatInput.addEventListener("input", () => {',
    '            sendBtn.disabled = !chatInput.value.trim();',
    '        });',
    '',
    '        // Handle enter key',
    '        chatInput.addEventListener("keydown", (e) => {',
    '            if (e.key === "Enter" && !e.shiftKey) {',
    '                e.preventDefault();',
    '                sendMessage();',
    '            }',
    '        });',
    '',
    '        sendBtn.addEventListener("click", () => sendMessage());',
    '',
    '        window.sendQuickAction = function(text) {',
    '            if (chatWindow.style.display === "none") {',
    '                chatWindow.style.display = "flex";',
    '            }',
    '            sendMessage(text);',
    '        };',
    '',
    '        // Simple markdown parser',
    '        function parseMarkdown(text) {',
    '            let html = text;',
    '            html = html.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");',
    '            html = html.replace(/```(\\w*)\\n([\\s\\S]*?)```/g, function(match, lang, code) {',
    '                return "<pre class=\\\"command-box\\\"><code>" + code.trim() + "</code></pre>";',
    '            });',
    '            html = html.replace(/`([^`]+)`/g, "<code style=\\\"background:rgba(255,140,66,0.1);padding:2px 6px;border-radius:4px;font-family:monospace;color:var(--accent);\\\">$1</code>");',
    '            html = html.replace(/\\*\\*([^*]+)\\*\\*/g, "<strong>$1</strong>");',
    '            html = html.replace(/\\n/g, "<br>");',
    '            return html;',
    '        }',
    '',
    '        let activeAssistantMessage = null;',
    '        let activeStatusElement = null;',
    '        let statusTimer = null;',
    '        let toolStartTime = 0;',
    '        let currentToolName = "";',
    '        let activeToolPanel = null;',
    '',
    '        function setStatus(text) {',
    '            if (statusTimer) { clearTimeout(statusTimer); statusTimer = null; }',
    '            if (!text) {',
    '                if (activeStatusElement) {',
    '                    activeStatusElement.remove();',
    '                    activeStatusElement = null;',
    '                }',
    '                return;',
    '            }',
    '            if (!activeStatusElement) {',
    '                activeStatusElement = document.createElement("div");',
    '                activeStatusElement.className = "message thinking";',
    '                messagesContainer.appendChild(activeStatusElement);',
    '            }',
    '',
    '            let html = \'<div class="thinking-header"><span class="thinking-spinner"></span><span>\' + escapeHtml(text) + \'</span></div>\';',
    '',
    '            activeStatusElement.innerHTML = html;',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '',
    '            // Show elapsed time after delay',
    '            if (text.includes("[诊断中]") || text.includes("[分析中]") || text.includes("[执行中]")) {',
    '                toolStartTime = Date.now();',
    '                statusTimer = setInterval(() => {',
    '                    if (!activeStatusElement || !activeStatusElement.isConnected) {',
    '                        clearInterval(statusTimer); statusTimer = null;',
    '                        return;',
    '                    }',
    '                    const elapsed = Math.round((Date.now() - toolStartTime) / 1000);',
    '                    const headerEl = activeStatusElement.querySelector(".thinking-header span:last-child");',
    '                    if (headerEl && !headerEl.textContent.includes("已耗时")) {',
    '                        headerEl.textContent = headerEl.textContent + " (" + elapsed + "s)";',
    '                    } else if (headerEl) {',
    '                        headerEl.textContent = text + " (" + elapsed + "s)";',
    '                    }',
    '                }, 1000);',
    '            }',
    '        }',
    '',
    '        function escapeHtml(text) {',
    '            const div = document.createElement("div");',
    '            div.textContent = text;',
    '            return div.innerHTML;',
    '        }',
    '',
    '        function parseJsonPayload(value) {',
    '            if (!value) return null;',
    '            if (typeof value === "object") return value;',
    '            try { return JSON.parse(value); } catch(e) { return null; }',
    '        }',
    '',
    '        function toolLabel(name) {',
    '            return name === "diagnose" ? "在线镜像检测" : name === "analyze" ? "环境分析" : name === "fix" ? "修复命令" : name;',
    '        }',
    '',
    '        function createToolPanel(name) {',
    '            const wrap = document.createElement("div");',
    '            wrap.className = "message tool-message";',
    '            wrap.innerHTML = \'<div class="tool-panel tool-\' + escapeHtml(name) + \'" data-tool="\' + escapeHtml(name) + \'">\' +',
    '                \'<div class="tool-panel-head"><div><span class="tool-kicker">Tool Calling</span><strong>\' + escapeHtml(toolLabel(name)) + \'</strong></div><span class="tool-state is-running">运行中</span></div>\' +',
    '                \'<div class="tool-panel-body"></div>\' +',
    '            \'</div>\';',
    '            messagesContainer.appendChild(wrap);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '            return wrap.querySelector(".tool-panel");',
    '        }',
    '',
    '        function getToolPanel(name) {',
    '            if (!activeToolPanel || !activeToolPanel.isConnected || activeToolPanel.dataset.tool !== name) {',
    '                activeToolPanel = createToolPanel(name);',
    '            }',
    '            return activeToolPanel;',
    '        }',
    '',
    '        function setToolState(panel, text, final) {',
    '            const state = panel.querySelector(".tool-state");',
    '            if (!state) return;',
    '            state.textContent = text;',
    '            state.className = "tool-state " + (final ? "is-done" : "is-running");',
    '        }',
    '',
    '        function statusBadge(status, hasError) {',
    '            if (hasError || status === "failed") return \'<span class="tool-badge bad">失败</span>\';',
    '            if (status === "lagging") return \'<span class="tool-badge warn">延迟同步</span>\';',
    '            if (status === "upstream") return \'<span class="tool-badge info">官方源</span>\';',
    '            return \'<span class="tool-badge ok">同步正常</span>\';',
    '        }',
    '',
    '        function renderDiagnosePanel(panel, data, partial) {',
    '            const body = panel.querySelector(".tool-panel-body");',
    '            if (!body) return;',
    '            const report = data && Array.isArray(data.report) ? data.report : [];',
    '            if (!report.length) {',
    '                body.innerHTML = \'<div class="tool-empty">正在等待镜像响应...</div>\';',
    '                setToolState(panel, "运行中", false);',
    '                return;',
    '            }',
    '            const rows = report.map(function(r) {',
    '                const latency = typeof r.latency_ms === "number" && r.latency_ms < 9999 ? r.latency_ms + " ms" : "-";',
    '                const shortHash = r.commit_hash ? escapeHtml(String(r.commit_hash).slice(0, 10)) : "-";',
    '                return \'<div class="tool-row">\' +',
    '                    \'<span class="tool-main" title="\' + escapeHtml(r.name || "") + \'">\' + escapeHtml(r.name || "Unknown") + \'</span>\' +',
    '                    \'<span class="tool-mono">\' + latency + \'</span>\' +',
    '                    statusBadge(r.sync_status, !!r.error) +',
    '                    \'<span class="tool-mono tool-hide-sm">\' + (r.http_status || 0) + \'</span>\' +',
    '                    \'<span class="tool-mono tool-hide-sm">\' + shortHash + \'</span>\' +',
    '                \'</div>\';',
    '            }).join("");',
    '            const source = escapeHtml(JSON.stringify(data, null, 2));',
    '            body.innerHTML = \'<div class="tool-grid-head"><span>镜像源</span><span>延迟</span><span>状态</span><span class="tool-hide-sm">HTTP</span><span class="tool-hide-sm">Commit</span></div>\' + rows +',
    '                (partial ? "" : \'<pre class="tool-copy-source">\' + source + \'</pre><button class="tool-copy-btn" onclick="copyToolPanelText(this)">复制报告</button>\');',
    '            setToolState(panel, partial ? "检测中" : "完成", !partial);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '        }',
    '',
    '        function renderAnalyzePanel(panel, data) {',
    '            const body = panel.querySelector(".tool-panel-body");',
    '            if (!body) return;',
    '            const issues = data && Array.isArray(data.issues) ? data.issues : [];',
    '            if (!issues.length) {',
    '                body.innerHTML = \'<div class="tool-empty">未发现明显配置问题。</div><pre class="tool-copy-source">\' + escapeHtml(JSON.stringify(data || {}, null, 2)) + \'</pre>\';',
    '                setToolState(panel, "完成", true);',
    '                return;',
    '            }',
    '            const html = issues.map(function(issue) {',
    '                const cls = issue.severity === "error" ? "bad" : issue.severity === "warning" ? "warn" : "info";',
    '                return \'<div class="issue-card">\' +',
    '                    \'<div class="issue-title"><span class="tool-badge \' + cls + \'">\' + escapeHtml(issue.severity || "info") + \'</span><strong>\' + escapeHtml(issue.title || "问题") + \'</strong></div>\' +',
    '                    \'<p>\' + escapeHtml(issue.message || "") + \'</p><p class="issue-suggest">\' + parseMarkdown(issue.suggestion || "") + \'</p>\' +',
    '                \'</div>\';',
    '            }).join("");',
    '            body.innerHTML = html + \'<pre class="tool-copy-source">\' + escapeHtml(JSON.stringify(data, null, 2)) + \'</pre><button class="tool-copy-btn" onclick="copyToolPanelText(this)">复制分析结果</button>\';',
    '            setToolState(panel, "完成", true);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '        }',
    '',
    '        function renderFixPanel(panel, content) {',
    '            const body = panel.querySelector(".tool-panel-body");',
    '            if (!body) return;',
    '            const text = String(content || "");',
    '            body.innerHTML = \'<pre class="command-box tool-copy-source"><code>\' + escapeHtml(text) + \'</code></pre><button class="tool-copy-btn" onclick="copyToolPanelText(this)">复制修复命令</button>\';',
    '            setToolState(panel, "完成", true);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '        }',
    '',
    '        function renderToolPanel(name, content, partial) {',
    '            const panel = getToolPanel(name);',
    '            if (name === "diagnose") renderDiagnosePanel(panel, parseJsonPayload(content), !!partial);',
    '            else if (name === "analyze") renderAnalyzePanel(panel, parseJsonPayload(content));',
    '            else if (name === "fix") renderFixPanel(panel, content);',
    '            else {',
    '                const body = panel.querySelector(".tool-panel-body");',
    '                if (body) body.innerHTML = \'<pre class="tool-copy-source">\' + escapeHtml(String(content || "")) + \'</pre><button class="tool-copy-btn" onclick="copyToolPanelText(this)">复制结果</button>\';',
    '                setToolState(panel, partial ? "运行中" : "完成", !partial);',
    '            }',
    '        }',
    '',
    '        window.copyToolPanelText = function(btn) {',
    '            const panel = btn.closest(".tool-panel");',
    '            const source = panel && panel.querySelector(".tool-copy-source");',
    '            const text = source ? source.textContent : "";',
    '            const done = function() { const old = btn.textContent; btn.textContent = "已复制"; setTimeout(function(){ btn.textContent = old; }, 1600); };',
    '            if (navigator.clipboard) navigator.clipboard.writeText(text).then(done).catch(done);',
    '            else { const t = document.createElement("textarea"); t.value = text; t.style.cssText = "position:fixed;opacity:0"; document.body.appendChild(t); t.select(); document.execCommand("copy"); document.body.removeChild(t); done(); }',
    '        };',
    '',
    '        async function sendMessage(overrideText) {',
    '            const text = (overrideText || chatInput.value).trim();',
    '            if (!text) return;',
    '',
    '            if (!overrideText) {',
    '                chatInput.value = "";',
    '                sendBtn.disabled = true;',
    '            }',
    '',
    '            // Remove previous quick-actions if any',
    '            const prevActions = messagesContainer.querySelector(".quick-actions");',
    '            if (prevActions) prevActions.remove();',
    '',
    '            // Append user message',
    '            const userMsgDiv = document.createElement("div");',
    '            userMsgDiv.className = "message user";',
    '            userMsgDiv.textContent = text;',
    '            messagesContainer.appendChild(userMsgDiv);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '',
    '            // Prepare Assistant bubble',
    '            activeAssistantMessage = document.createElement("div");',
    '            activeAssistantMessage.className = "message system";',
    '            activeAssistantMessage.innerHTML = "<span style=\\\"color:var(--text-muted);\\\">处理中...</span>";',
    '            messagesContainer.appendChild(activeAssistantMessage);',
    '            messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '',
    '            let responseText = "";',
    '            let lastEventTime = Date.now();',
    '            let requestTimeout = null;',
    '            let requestStartTime = Date.now();',
    '            ',
    '            try {',
    '                const response = await fetch("/chat", {',
    '                    method: "POST",',
    '                    headers: {',
    '                        "Content-Type": "application/json",',
    '                        "makers-conversation-id": convId',
    '                    },',
    '                    body: JSON.stringify({ message: text })',
    '                });',
    '',
    '                if (!response.ok) {',
    '                    throw new Error("HTTP " + response.status);',
    '                }',
    '',
    '                const reader = response.body.getReader();',
    '                const decoder = new TextDecoder();',
    '                let buffer = "";',
    '',
    '                setStatus("[思考中] 正在分析...");',
    '                requestTimeout = setInterval(() => {',
    '                    if (Date.now() - lastEventTime > 25000) {',
    '                        clearInterval(requestTimeout); requestTimeout = null;',
    '                        reader.cancel();',
    '                        setStatus(null);',
    '                        if (activeToolPanel) setToolState(activeToolPanel, "超时", true);',
    '                        activeAssistantMessage.innerHTML = "<span style=\'color:red\'>请求超时，请重试。</span>";',
    '                    }',
    '                }, 1000);',
    '',
    '                while (true) {',
    '                    const { done, value } = await reader.read();',
    '                    if (done) break;',
    '                    lastEventTime = Date.now();',
    '',
    '                    buffer += decoder.decode(value, { stream: true });',
    '                    const lines = buffer.split("\\n\\n");',
    '                    buffer = lines.pop() || "";',
    '',
    '                    for (const line of lines) {',
    '                        const trimmed = line.trim();',
    '                        if (!trimmed || !trimmed.startsWith("data: ")) continue;',
    '',
    '                        const payloadStr = trimmed.slice(6);',
    '                        if (payloadStr === "[DONE]") {',
    '                            setStatus(null);',
    '                            continue;',
    '                        }',
    '',
    '                        try {',
    '                            const event = JSON.parse(payloadStr);',
    '                            ',
    '                            if (event.type === "ping") {',
    '                                continue;',
    '                            }',
    '                            ',
    '                            if (event.type === "thinking") {',
    '                                setStatus("[思考中] " + event.content);',
    '                                currentToolName = "";',
    '                            } else if (event.type === "tool_call") {',
    '                                currentToolName = event.name;',
    '                                activeToolPanel = createToolPanel(event.name);',
    '                                if (event.name === "diagnose") renderDiagnosePanel(activeToolPanel, { ok: true, partial: true, report: [] }, true);',
    '                                else setToolState(activeToolPanel, "运行中", false);',
    '                                setStatus("[工具调用] " + toolLabel(event.name));',
    '                            } else if (event.type === "tool_result") {',
    '                                renderToolPanel(event.name || currentToolName || "tool", event.content, event.partial);',
    '                                if (!event.partial) {',
    '                                    setStatus(null);',
    '                                    currentToolName = "";',
    '                                }',
    '                            } else if (event.type === "ai_response") {',
    '                                if (event.content && (event.content.includes("正在为您运行在线镜像检测") || event.content.includes("正在运行在线镜像检测") || event.content.includes("正在检测"))) {',
    '                                    continue;',
    '                                }',
    '                                responseText += event.content;',
    '                                activeAssistantMessage.innerHTML = parseMarkdown(responseText);',
    '                                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '                            } else if (event.type === "error_message") {',
    '                                setStatus(null);',
    '                                const errorDiv = document.createElement("div");',
    '                                errorDiv.className = "message thinking";',
    '                                errorDiv.style.borderColor = "red";',
    '                                errorDiv.style.color = "red";',
    '                                errorDiv.textContent = "[错误] " + event.content;',
    '                                messagesContainer.appendChild(errorDiv);',
    '                                messagesContainer.scrollTop = messagesContainer.scrollHeight;',
    '                            }',
    '                        } catch (e) {',
    '                            console.error("Error parsing SSE line:", e);',
    '                        }',
    '                    }',
    '                }',
    '                ',
    '                setStatus(null);',
    '',
    '            } catch (err) {',
    '                if (requestTimeout) { clearInterval(requestTimeout); requestTimeout = null; }',
    '                setStatus(null);',
    '                activeAssistantMessage.innerHTML = "<span style=\\\"color:red;\\\">连接失败，请重试。</span>";',
    '                console.error("Chat error:", err);',
    '            } finally {',
    '                if (requestTimeout) { clearInterval(requestTimeout); requestTimeout = null; }',
    '            }',
    '        }',
    '    })();',
    '</script>',
  ];
  return '\n    ' + lines.join('\n');
}
